// @license
// Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
// This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
// The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
// The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
// Code distributed by Google as part of the polymer project is also
// subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

(function(){function a(m,n){return m.replace(g,function(q,p,t,r){return p+"'"+b(t.replace(/["']/g,""),n)+"'"+r})}function b(m,n){if(m&&k.test(m))return m;n=n.body.__urlResolver||(n.body.__urlResolver=n.createElement("a"));n.href=m;return n.href||m}function c(m){return m.substring(0,m.lastIndexOf("/")+1)}var d,e,g=/(url\()([^)]*)(\))/g,h={"*":["href","src","style","url"],form:["action"]},k=/(^\/)|(^#)|(^[\w-\d]*:)/,l=/\{\{|\[\[/;Polymer.ResolveUrl={resolveCss:a,resolveAttrs:function(m,n){for(var q in h)for(var p=
    h[q],t=0,r=p.length,v,u,w;t<r&&(v=p[t]);t++)("*"===q||m.localName===q)&&(w=(u=m.attributes[v])&&u.value)&&0>w.search(l)&&(u.value="style"===v?a(w,n):b(w,n))},resolveUrl:function(m,n){d||(d=document.implementation.createHTMLDocument("temp"),e=d.createElement("base"),d.head.appendChild(e));e.href=n;return b(m,d)},pathFromUrl:c};Polymer.rootPath=Polymer.Settings.rootPath||c(document.baseURI||window.location.href)})();
    Polymer.Base._addFeature({_prepTemplate:function(){var a;void 0===this._template&&(this._template=(a=Polymer.DomModule.import(this.is))&&a.querySelector("template"));if(a){var b=a.getAttribute("assetpath")||"";a=Polymer.ResolveUrl.resolveUrl(b,a.ownerDocument.baseURI);this._importPath=Polymer.ResolveUrl.pathFromUrl(a)}else this._importPath="";this._template&&this._template.hasAttribute("is")&&this._warn(this._logf("_prepTemplate","top-level Polymer template must not be a type-extension, found",this._template,
    "Move inside simple \x3ctemplate\x3e."));this._template&&!this._template.content&&window.HTMLTemplateElement&&HTMLTemplateElement.decorate&&HTMLTemplateElement.decorate(this._template)},_stampTemplate:function(){this._template&&(this.root=this.instanceTemplate(this._template))},instanceTemplate:function(a){return document.importNode(a._content||a.content,!0)}});
    (function(){var a=Polymer.Base.attachedCallback,b=Polymer.Base.detachedCallback;Polymer.Base._addFeature({_hostStack:[],ready:function(){},_registerHost:function(c){(this.dataHost=c=c||Polymer.Base._hostStack[Polymer.Base._hostStack.length-1])&&c._clients&&c._clients.push(this);this._clients=null;this._clientsReadied=!1},_beginHosting:function(){Polymer.Base._hostStack.push(this);this._clients||(this._clients=[])},_endHosting:function(){Polymer.Base._hostStack.pop()},_tryReady:function(){this._readied=
    !1;this._canReady()&&this._ready()},_canReady:function(){return!this.dataHost||this.dataHost._clientsReadied},_ready:function(){this._beforeClientsReady();this._template&&(this._setupRoot(),this._readyClients());this._clientsReadied=!0;this._clients=null;this._afterClientsReady();this._readySelf()},_readyClients:function(){this._beginDistribute();var c=this._clients;if(c)for(var d=0,e=c.length,g;d<e&&(g=c[d]);d++)g._ready();this._finishDistribute()},_readySelf:function(){for(var c=0,d;c<this.behaviors.length;c++)d=
    this.behaviors[c],d.ready&&d.ready.call(this);this.ready&&this.ready();this._readied=!0;this._attachedPending&&(this._attachedPending=!1,this.attachedCallback())},_beforeClientsReady:function(){},_afterClientsReady:function(){},_beforeAttached:function(){},attachedCallback:function(){this._readied?(this._beforeAttached(),a.call(this)):this._attachedPending=!0},detachedCallback:function(){this._readied?b.call(this):this._attachedPending=!1}})})();
    Polymer.ArraySplice=function(){function a(c,d,e){return{index:c,removed:d,addedCount:e}}function b(){}b.prototype={calcEditDistances:function(c,d,e,g,h,k){k=k-h+1;e=e-d+1;for(var l=Array(k),m=0;m<k;m++)l[m]=Array(e),l[m][0]=m;for(var n=0;n<e;n++)l[0][n]=n;for(m=1;m<k;m++)for(n=1;n<e;n++)if(this.equals(c[d+n-1],g[h+m-1]))l[m][n]=l[m-1][n-1];else{var q=l[m-1][n]+1,p=l[m][n-1]+1;l[m][n]=q<p?q:p}return l},spliceOperationsFromEditDistances:function(c){for(var d=c.length-1,e=c[0].length-1,g=c[d][e],h=[];0<
    d||0<e;)if(0==d)h.push(2),e--;else if(0==e)h.push(3),d--;else{var k=c[d-1][e-1],l=c[d-1][e],m=c[d][e-1];var n=l<m?l<k?l:k:m<k?m:k;n==k?(k==g?h.push(0):(h.push(1),g=k),d--,e--):n==l?(h.push(3),d--,g=l):(h.push(2),e--,g=m)}h.reverse();return h},calcSplices:function(c,d,e,g,h,k){var l=0,m=0,n=Math.min(e-d,k-h);0==d&&0==h&&(l=this.sharedPrefix(c,g,n));e==c.length&&k==g.length&&(m=this.sharedSuffix(c,g,n-l));d+=l;h+=l;e-=m;k-=m;if(0==e-d&&0==k-h)return[];if(d==e){for(c=a(d,[],0);h<k;)c.removed.push(g[h++]);
    return[c]}if(h==k)return[a(d,[],e-d)];k=this.spliceOperationsFromEditDistances(this.calcEditDistances(c,d,e,g,h,k));c=void 0;e=[];for(l=0;l<k.length;l++)switch(k[l]){case 0:c&&(e.push(c),c=void 0);d++;h++;break;case 1:c||(c=a(d,[],0));c.addedCount++;d++;c.removed.push(g[h]);h++;break;case 2:c||(c=a(d,[],0));c.addedCount++;d++;break;case 3:c||(c=a(d,[],0)),c.removed.push(g[h]),h++}c&&e.push(c);return e},sharedPrefix:function(c,d,e){for(var g=0;g<e;g++)if(!this.equals(c[g],d[g]))return g;return e},
    sharedSuffix:function(c,d,e){for(var g=c.length,h=d.length,k=0;k<e&&this.equals(c[--g],d[--h]);)k++;return k},calculateSplices:function(c,d){return this.calcSplices(c,0,c.length,d,0,d.length)},equals:function(c,d){return c===d}};return new b}();
    Polymer.domInnerHTML=function(){function a(k){switch(k){case "\x26":return"\x26amp;";case "\x3c":return"\x26lt;";case "\x3e":return"\x26gt;";case '"':return"\x26quot;";case "\u00a0":return"\x26nbsp;"}}function b(k){for(var l={},m=0;m<k.length;m++)l[k[m]]=!0;return l}function c(k,l){k instanceof HTMLTemplateElement&&(k=k.content);for(var m="",n=Polymer.dom(k).childNodes,q=0,p=n.length,t;q<p&&(t=n[q]);q++){a:{var r=t;var v=k;var u=l;switch(r.nodeType){case Node.ELEMENT_NODE:for(var w=r.localName,x=
    "\x3c"+w,A=r.attributes,y=0;v=A[y];y++)x+=" "+v.name+'\x3d"'+v.value.replace(d,a)+'"';x+="\x3e";r=g[w]?x:x+c(r,u)+"\x3c/"+w+"\x3e";break a;case Node.TEXT_NODE:r=r.data;r=v&&h[v.localName]?r:r.replace(e,a);break a;case Node.COMMENT_NODE:r="\x3c!--"+r.data+"--\x3e";break a;default:throw console.error(r),Error("not implemented");}}m+=r}return m}var d=/[&\u00A0"]/g,e=/[&\u00A0<>]/g,g=b("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),h=b("style script xmp iframe noembed noframes plaintext noscript".split(" "));
    return{getInnerHTML:c}}();
    (function(){var a=Element.prototype.insertBefore,b=Element.prototype.appendChild,c=Element.prototype.removeChild;Polymer.TreeApi={arrayCopyChildNodes:function(d){var e=[],g=0;for(d=d.firstChild;d;d=d.nextSibling)e[g++]=d;return e},arrayCopyChildren:function(d){var e=[],g=0;for(d=d.firstElementChild;d;d=d.nextElementSibling)e[g++]=d;return e},arrayCopy:function(d){for(var e=d.length,g=Array(e),h=0;h<e;h++)g[h]=d[h];return g}};Polymer.TreeApi.Logical={hasParentNode:function(d){return!(!d.__dom||!d.__dom.parentNode)},
    hasChildNodes:function(d){return!(!d.__dom||void 0===d.__dom.childNodes)},getChildNodes:function(d){return this.hasChildNodes(d)?this._getChildNodes(d):d.childNodes},_getChildNodes:function(d){if(!d.__dom.childNodes){d.__dom.childNodes=[];for(var e=d.__dom.firstChild;e;e=e.__dom.nextSibling)d.__dom.childNodes.push(e)}return d.__dom.childNodes},getParentNode:function(d){return d.__dom&&void 0!==d.__dom.parentNode?d.__dom.parentNode:d.parentNode},getFirstChild:function(d){return d.__dom&&void 0!==d.__dom.firstChild?
    d.__dom.firstChild:d.firstChild},getLastChild:function(d){return d.__dom&&void 0!==d.__dom.lastChild?d.__dom.lastChild:d.lastChild},getNextSibling:function(d){return d.__dom&&void 0!==d.__dom.nextSibling?d.__dom.nextSibling:d.nextSibling},getPreviousSibling:function(d){return d.__dom&&void 0!==d.__dom.previousSibling?d.__dom.previousSibling:d.previousSibling},getFirstElementChild:function(d){return d.__dom&&void 0!==d.__dom.firstChild?this._getFirstElementChild(d):d.firstElementChild},_getFirstElementChild:function(d){for(d=
    d.__dom.firstChild;d&&d.nodeType!==Node.ELEMENT_NODE;)d=d.__dom.nextSibling;return d},getLastElementChild:function(d){return d.__dom&&void 0!==d.__dom.lastChild?this._getLastElementChild(d):d.lastElementChild},_getLastElementChild:function(d){for(d=d.__dom.lastChild;d&&d.nodeType!==Node.ELEMENT_NODE;)d=d.__dom.previousSibling;return d},getNextElementSibling:function(d){return d.__dom&&void 0!==d.__dom.nextSibling?this._getNextElementSibling(d):d.nextElementSibling},_getNextElementSibling:function(d){for(d=
    d.__dom.nextSibling;d&&d.nodeType!==Node.ELEMENT_NODE;)d=d.__dom.nextSibling;return d},getPreviousElementSibling:function(d){return d.__dom&&void 0!==d.__dom.previousSibling?this._getPreviousElementSibling(d):d.previousElementSibling},_getPreviousElementSibling:function(d){for(d=d.__dom.previousSibling;d&&d.nodeType!==Node.ELEMENT_NODE;)d=d.__dom.previousSibling;return d},saveChildNodes:function(d){if(!this.hasChildNodes(d)){d.__dom=d.__dom||{};d.__dom.firstChild=d.firstChild;d.__dom.lastChild=d.lastChild;
    d.__dom.childNodes=[];for(var e=d.firstChild;e;e=e.nextSibling)e.__dom=e.__dom||{},e.__dom.parentNode=d,d.__dom.childNodes.push(e),e.__dom.nextSibling=e.nextSibling,e.__dom.previousSibling=e.previousSibling}},recordInsertBefore:function(d,e,g){e.__dom.childNodes=null;if(d.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(d=d.firstChild;d;d=d.nextSibling)this._linkNode(d,e,g);else this._linkNode(d,e,g)},_linkNode:function(d,e,g){d.__dom=d.__dom||{};e.__dom=e.__dom||{};g&&(g.__dom=g.__dom||{});d.__dom.previousSibling=
    g?g.__dom.previousSibling:e.__dom.lastChild;d.__dom.previousSibling&&(d.__dom.previousSibling.__dom.nextSibling=d);d.__dom.nextSibling=g||null;d.__dom.nextSibling&&(d.__dom.nextSibling.__dom.previousSibling=d);d.__dom.parentNode=e;g?g===e.__dom.firstChild&&(e.__dom.firstChild=d):(e.__dom.lastChild=d,e.__dom.firstChild||(e.__dom.firstChild=d));e.__dom.childNodes=null},recordRemoveChild:function(d,e){d.__dom=d.__dom||{};e.__dom=e.__dom||{};d===e.__dom.firstChild&&(e.__dom.firstChild=d.__dom.nextSibling);
    d===e.__dom.lastChild&&(e.__dom.lastChild=d.__dom.previousSibling);var g=d.__dom.previousSibling,h=d.__dom.nextSibling;g&&(g.__dom.nextSibling=h);h&&(h.__dom.previousSibling=g);d.__dom.parentNode=d.__dom.previousSibling=d.__dom.nextSibling=void 0;e.__dom.childNodes=null}};Polymer.TreeApi.Composed={getChildNodes:function(d){return Polymer.TreeApi.arrayCopyChildNodes(d)},getParentNode:function(d){return d.parentNode},clearChildNodes:function(d){d.textContent=""},insertBefore:function(d,e,g){return a.call(d,
    e,g||null)},appendChild:function(d,e){return b.call(d,e)},removeChild:function(d,e){return c.call(d,e)}}})();
    Polymer.DomApi=function(){function a(h){this.node=d?a.wrap(h):h}var b=Polymer.Settings,c=Polymer.TreeApi,d=b.hasShadow&&!b.nativeShadow;a.wrap=window.wrap?window.wrap:function(h){return h};a.prototype={flush:function(){Polymer.dom.flush()},deepContains:function(h){if(this.node.contains(h))return!0;var k=h;for(h=h.ownerDocument;k&&k!==h&&k!==this.node;)k=Polymer.dom(k).parentNode||k.host;return k===this.node},queryDistributedElements:function(h){for(var k=this.getEffectiveChildNodes(),l=[],m=0,n=k.length,
    q;m<n&&(q=k[m]);m++)q.nodeType===Node.ELEMENT_NODE&&a.matchesSelector.call(q,h)&&l.push(q);return l},getEffectiveChildNodes:function(){for(var h=[],k=this.childNodes,l=0,m=k.length,n;l<m&&(n=k[l]);l++)if(n.localName===e)for(var q=g(n).getDistributedNodes(),p=0;p<q.length;p++)h.push(q[p]);else h.push(n);return h},observeNodes:function(h){if(h)return this.observer||(this.observer=this.node.localName===e?new a.DistributedNodesObserver(this):new a.EffectiveNodesObserver(this)),this.observer.addListener(h)},
    unobserveNodes:function(h){this.observer&&this.observer.removeListener(h)},notifyObserver:function(){this.observer&&this.observer.notify()},_query:function(h,k,l){k=k||this.node;var m=[];this._queryElements(c.Logical.getChildNodes(k),h,l,m);return m},_queryElements:function(h,k,l,m){for(var n=0,q=h.length,p;n<q&&(p=h[n]);n++)if(p.nodeType===Node.ELEMENT_NODE&&this._queryElement(p,k,l,m))return!0},_queryElement:function(h,k,l,m){var n=k(h);n&&m.push(h);if(l&&l(n))return n;this._queryElements(c.Logical.getChildNodes(h),
    k,l,m)}};var e=a.CONTENT="content",g=a.factory=function(h){h=h||document;h.__domApi||(h.__domApi=new a.ctor(h));return h.__domApi};a.hasApi=function(h){return!!h.__domApi};a.ctor=a;Polymer.dom=function(h,k){return h instanceof Event?Polymer.EventApi.factory(h):a.factory(h,k)};b=Element.prototype;a.matchesSelector=b.matches||b.matchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector||b.webkitMatchesSelector;return a}();
    (function(){var a=Polymer.DomApi,b=a.factory,c=Polymer.TreeApi,d=Polymer.domInnerHTML.getInnerHTML,e=a.CONTENT;if(!Polymer.Settings.useShadow){var g=Element.prototype.cloneNode,h=Document.prototype.importNode;Polymer.Base.mixin(a.prototype,{_lazyDistribute:function(k){k.shadyRoot&&k.shadyRoot._distributionClean&&(k.shadyRoot._distributionClean=!1,Polymer.dom.addDebouncer(k.debounce("_distribute",k._distributeContent)))},appendChild:function(k){return this.insertBefore(k)},insertBefore:function(k,
    l){if(l&&c.Logical.getParentNode(l)!==this.node)throw Error("The ref_node to be inserted before is not a child of this node");if(k.nodeType!==Node.DOCUMENT_FRAGMENT_NODE){var m=c.Logical.getParentNode(k);m?(a.hasApi(m)&&b(m).notifyObserver(),this._removeNode(k)):this._removeOwnerShadyRoot(k)}this._addNode(k,l)||(l&&(l=l.localName===e?this._firstComposedNode(l):l),m=this.node._isShadyRoot?this.node.host:this.node,l?c.Composed.insertBefore(m,k,l):c.Composed.appendChild(m,k));this.notifyObserver();return k},
    _addNode:function(k,l){var m=this.getOwnerRoot();if(m){var n=this._maybeAddInsertionPoint(k,this.node);m._invalidInsertionPoints||(m._invalidInsertionPoints=n);this._addNodeToHost(m.host,k)}c.Logical.hasChildNodes(this.node)&&c.Logical.recordInsertBefore(k,this.node,l);if(l=this._maybeDistribute(k)||this.node.shadyRoot)if(k.nodeType===Node.DOCUMENT_FRAGMENT_NODE)for(;k.firstChild;)c.Composed.removeChild(k,k.firstChild);else(m=c.Composed.getParentNode(k))&&c.Composed.removeChild(m,k);return l},removeChild:function(k){if(c.Logical.getParentNode(k)!==
    this.node)throw Error("The node to be removed is not a child of this node: "+k);if(!this._removeNode(k)){var l=this.node._isShadyRoot?this.node.host:this.node;l===c.Composed.getParentNode(k)&&c.Composed.removeChild(l,k)}this.notifyObserver();return k},_removeNode:function(k){var l=c.Logical.hasParentNode(k)&&c.Logical.getParentNode(k),m=this._ownerShadyRootForNode(k);if(l){var n=b(k)._maybeDistributeParent();c.Logical.recordRemoveChild(k,l);m&&this._removeDistributedChildren(m,k)&&(m._invalidInsertionPoints=
    !0,this._lazyDistribute(m.host))}this._removeOwnerShadyRoot(k);m&&this._removeNodeFromHost(m.host,k);return n},replaceChild:function(k,l){this.insertBefore(k,l);this.removeChild(l);return k},_hasCachedOwnerRoot:function(k){return void 0!==k._ownerShadyRoot},getOwnerRoot:function(){return this._ownerShadyRootForNode(this.node)},_ownerShadyRootForNode:function(k){if(k){var l=k._ownerShadyRoot;void 0===l&&(l=k._isShadyRoot?k:(l=c.Logical.getParentNode(k))?l._isShadyRoot?l:this._ownerShadyRootForNode(l):
    null,l||document.documentElement.contains(k))&&(k._ownerShadyRoot=l);return l}},_maybeDistribute:function(k){var l=k.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&!k.__noContent&&b(k).querySelector(e),m=l&&c.Logical.getParentNode(l).nodeType!==Node.DOCUMENT_FRAGMENT_NODE;(k=l||k.localName===e)&&(l=this.getOwnerRoot())&&this._lazyDistribute(l.host);(l=this._nodeNeedsDistribution(this.node))&&this._lazyDistribute(this.node);return l||k&&!m},_maybeAddInsertionPoint:function(k,l){if(k.nodeType!==Node.DOCUMENT_FRAGMENT_NODE||
    k.__noContent)k.localName===e&&(c.Logical.saveChildNodes(l),c.Logical.saveChildNodes(k),t=!0);else for(var m=b(k).querySelectorAll(e),n=0,q,p;n<m.length&&(q=m[n]);n++){p=c.Logical.getParentNode(q);p===k&&(p=l);p=this._maybeAddInsertionPoint(q,p);var t=t||p}return t},_updateInsertionPoints:function(k){k=k.shadyRoot._insertionPoints=b(k.shadyRoot).querySelectorAll(e);for(var l=0,m;l<k.length;l++)m=k[l],c.Logical.saveChildNodes(m),c.Logical.saveChildNodes(c.Logical.getParentNode(m))},_nodeNeedsDistribution:function(k){return k&&
    k.shadyRoot&&a.hasInsertionPoint(k.shadyRoot)},_addNodeToHost:function(k,l){k._elementAdd&&k._elementAdd(l)},_removeNodeFromHost:function(k,l){k._elementRemove&&k._elementRemove(l)},_removeDistributedChildren:function(k,l){k=k._insertionPoints;for(var m=0;m<k.length;m++){var n=k[m];if(this._contains(l,n)){n=b(n).getDistributedNodes();for(var q=0;q<n.length;q++){var p=!0;var t=n[q],r=c.Composed.getParentNode(t);r&&c.Composed.removeChild(r,t)}}}return p},_contains:function(k,l){for(;l;){if(l==k)return!0;
    l=c.Logical.getParentNode(l)}},_removeOwnerShadyRoot:function(k){if(this._hasCachedOwnerRoot(k))for(var l=c.Logical.getChildNodes(k),m=0,n=l.length,q;m<n&&(q=l[m]);m++)this._removeOwnerShadyRoot(q);k._ownerShadyRoot=void 0},_firstComposedNode:function(k){for(var l=b(k).getDistributedNodes(),m=0,n=l.length,q,p;m<n&&(q=l[m]);m++)if(p=b(q).getDestinationInsertionPoints(),p[p.length-1]===k)return q},querySelector:function(k){return this._query(function(l){return a.matchesSelector.call(l,k)},this.node,
    function(l){return!!l})[0]||null},querySelectorAll:function(k){return this._query(function(l){return a.matchesSelector.call(l,k)},this.node)},getDestinationInsertionPoints:function(){return this.node._destinationInsertionPoints||[]},getDistributedNodes:function(){return this.node._distributedNodes||[]},_clear:function(){for(;this.childNodes.length;)this.removeChild(this.childNodes[0])},setAttribute:function(k,l){this.node.setAttribute(k,l);this._maybeDistributeParent()},removeAttribute:function(k){this.node.removeAttribute(k);
    this._maybeDistributeParent()},_maybeDistributeParent:function(){if(this._nodeNeedsDistribution(this.parentNode))return this._lazyDistribute(this.parentNode),!0},cloneNode:function(k){var l=g.call(this.node,!1);if(k){k=this.childNodes;for(var m=b(l),n=0,q;n<k.length;n++)q=b(k[n]).cloneNode(!0),m.appendChild(q)}return l},importNode:function(k,l){var m=this.node instanceof Document?this.node:this.node.ownerDocument,n=h.call(m,k,!1);if(l){k=c.Logical.getChildNodes(k);l=b(n);for(var q=0,p;q<k.length;q++)p=
    b(m).importNode(k[q],!0),l.appendChild(p)}return n},_getComposedInnerHTML:function(){return d(this.node,!0)}});Object.defineProperties(a.prototype,{activeElement:{get:function(){var k=document.activeElement;if(!k)return null;var l=!!this.node._isShadyRoot;if(!(this.node===document||l&&this.node.host!==k&&this.node.host.contains(k)))return null;for(l=b(k).getOwnerRoot();l&&l!==this.node;)k=l.host,l=b(k).getOwnerRoot();return this.node===document?l?null:k:l===this.node?k:null},configurable:!0},childNodes:{get:function(){var k=
    c.Logical.getChildNodes(this.node);return Array.isArray(k)?k:c.arrayCopyChildNodes(this.node)},configurable:!0},children:{get:function(){return c.Logical.hasChildNodes(this.node)?Array.prototype.filter.call(this.childNodes,function(k){return k.nodeType===Node.ELEMENT_NODE}):c.arrayCopyChildren(this.node)},configurable:!0},parentNode:{get:function(){return c.Logical.getParentNode(this.node)},configurable:!0},firstChild:{get:function(){return c.Logical.getFirstChild(this.node)},configurable:!0},lastChild:{get:function(){return c.Logical.getLastChild(this.node)},
    configurable:!0},nextSibling:{get:function(){return c.Logical.getNextSibling(this.node)},configurable:!0},previousSibling:{get:function(){return c.Logical.getPreviousSibling(this.node)},configurable:!0},firstElementChild:{get:function(){return c.Logical.getFirstElementChild(this.node)},configurable:!0},lastElementChild:{get:function(){return c.Logical.getLastElementChild(this.node)},configurable:!0},nextElementSibling:{get:function(){return c.Logical.getNextElementSibling(this.node)},configurable:!0},
    previousElementSibling:{get:function(){return c.Logical.getPreviousElementSibling(this.node)},configurable:!0},textContent:{get:function(){var k=this.node.nodeType;if(k===Node.TEXT_NODE||k===Node.COMMENT_NODE)return this.node.textContent;k=[];for(var l=0,m=this.childNodes,n;n=m[l];l++)n.nodeType!==Node.COMMENT_NODE&&k.push(n.textContent);return k.join("")},set:function(k){var l=this.node.nodeType;l===Node.TEXT_NODE||l===Node.COMMENT_NODE?this.node.textContent=k:(this._clear(),k&&this.appendChild(document.createTextNode(k)))},
    configurable:!0},innerHTML:{get:function(){var k=this.node.nodeType;return k===Node.TEXT_NODE||k===Node.COMMENT_NODE?null:d(this.node)},set:function(k){var l=this.node.nodeType;if(l!==Node.TEXT_NODE||l!==Node.COMMENT_NODE)for(this._clear(),l=document.createElement("div"),l.innerHTML=k,k=c.arrayCopyChildNodes(l),l=0;l<k.length;l++)this.appendChild(k[l])},configurable:!0}});a.hasInsertionPoint=function(k){return!(!k||!k._insertionPoints.length)}}})();
    (function(){var a=Polymer.TreeApi,b=Polymer.DomApi;if(Polymer.Settings.useShadow){Polymer.Base.mixin(b.prototype,{querySelectorAll:function(e){return a.arrayCopy(this.node.querySelectorAll(e))},getOwnerRoot:function(){for(var e=this.node;e;){if(e.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&e.host)return e;e=e.parentNode}},importNode:function(e,g){return(this.node instanceof Document?this.node:this.node.ownerDocument).importNode(e,g)},getDestinationInsertionPoints:function(){var e=this.node.getDestinationInsertionPoints&&
    this.node.getDestinationInsertionPoints();return e?a.arrayCopy(e):[]},getDistributedNodes:function(){var e=this.node.getDistributedNodes&&this.node.getDistributedNodes();return e?a.arrayCopy(e):[]}});Object.defineProperties(b.prototype,{activeElement:{get:function(){var e=b.wrap(this.node),g=e.activeElement;return e.contains(g)?g:null},configurable:!0},childNodes:{get:function(){return a.arrayCopyChildNodes(this.node)},configurable:!0},children:{get:function(){return a.arrayCopyChildren(this.node)},
    configurable:!0},textContent:{get:function(){return this.node.textContent},set:function(e){return this.node.textContent=e},configurable:!0},innerHTML:{get:function(){return this.node.innerHTML},set:function(e){return this.node.innerHTML=e},configurable:!0}});var c=function(e){b.prototype[e]=function(){return this.node[e].apply(this.node,arguments)}};(function(e){for(var g=0;g<e.length;g++)c(e[g])})("cloneNode appendChild insertBefore removeChild replaceChild setAttribute removeAttribute querySelector".split(" "));
    var d=function(e){Object.defineProperty(b.prototype,e,{get:function(){return this.node[e]},configurable:!0})};(function(e){for(var g=0;g<e.length;g++)d(e[g])})("parentNode firstChild lastChild nextSibling previousSibling firstElementChild lastElementChild nextElementSibling previousElementSibling".split(" "))}})();
    Polymer.Base.mixin(Polymer.dom,{_flushGuard:0,_FLUSH_MAX:100,_needsTakeRecords:!Polymer.Settings.useNativeCustomElements,_debouncers:[],_staticFlushList:[],_finishDebouncer:null,flush:function(){this._flushGuard=0;for(this._prepareFlush();this._debouncers.length&&this._flushGuard<this._FLUSH_MAX;){for(;this._debouncers.length;)this._debouncers.shift().complete();this._finishDebouncer&&this._finishDebouncer.complete();this._prepareFlush();this._flushGuard++}this._flushGuard>=this._FLUSH_MAX&&console.warn("Polymer.dom.flush aborted. Flush may not be complete.")},
    _prepareFlush:function(){this._needsTakeRecords&&CustomElements.takeRecords();for(var a=0;a<this._staticFlushList.length;a++)this._staticFlushList[a]()},addStaticFlush:function(a){this._staticFlushList.push(a)},removeStaticFlush:function(a){a=this._staticFlushList.indexOf(a);0<=a&&this._staticFlushList.splice(a,1)},addDebouncer:function(a){this._debouncers.push(a);this._finishDebouncer=Polymer.Debounce(this._finishDebouncer,this._finishFlush)},_finishFlush:function(){Polymer.dom._debouncers=[]}});
    Polymer.EventApi=function(){var a=Polymer.DomApi.ctor,b=Polymer.Settings;a.Event=function(c){this.event=c};a.Event.prototype=b.useShadow?{get rootTarget(){return this.event.path[0]},get localTarget(){return this.event.target},get path(){var c=this.event.path;Array.isArray(c)||(c=Array.prototype.slice.call(c));return c}}:{get rootTarget(){return this.event.target},get localTarget(){var c=this.event.currentTarget;c=c&&Polymer.dom(c).getOwnerRoot();for(var d=this.path,e=0;e<d.length;e++)if(Polymer.dom(d[e]).getOwnerRoot()===
    c)return d[e]},get path(){if(!this.event._path){for(var c=[],d=this.rootTarget;d;){c.push(d);var e=Polymer.dom(d).getDestinationInsertionPoints();if(e.length){for(d=0;d<e.length-1;d++)c.push(e[d]);d=e[e.length-1]}else d=Polymer.dom(d).parentNode||d.host}c.push(window);this.event._path=c}return this.event._path}};return{factory:function(c){c.__eventApi||(c.__eventApi=new a.Event(c));return c.__eventApi}}}();
    (function(){var a=Polymer.DomApi.ctor,b=Polymer.Settings.useShadow;Object.defineProperty(a.prototype,"classList",{get:function(){this._classList||(this._classList=new a.ClassList(this));return this._classList},configurable:!0});a.ClassList=function(c){this.domApi=c;this.node=c.node};a.ClassList.prototype={add:function(){this.node.classList.add.apply(this.node.classList,arguments);this._distributeParent()},remove:function(){this.node.classList.remove.apply(this.node.classList,arguments);this._distributeParent()},
    toggle:function(){this.node.classList.toggle.apply(this.node.classList,arguments);this._distributeParent()},_distributeParent:function(){b||this.domApi._maybeDistributeParent()},contains:function(){return this.node.classList.contains.apply(this.node.classList,arguments)}}})();
    (function(){var a=Polymer.DomApi.ctor,b=Polymer.Settings;a.EffectiveNodesObserver=function(e){this.domApi=e;this.node=this.domApi.node;this._listeners=[]};a.EffectiveNodesObserver.prototype={addListener:function(e){this._isSetup||(this._setup(),this._isSetup=!0);e={fn:e,_nodes:[]};this._listeners.push(e);this._scheduleNotify();return e},removeListener:function(e){var g=this._listeners.indexOf(e);0<=g&&(this._listeners.splice(g,1),e._nodes=[]);this._hasListeners()||(this._cleanup(),this._isSetup=!1)},
    _setup:function(){this._observeContentElements(this.domApi.childNodes)},_cleanup:function(){this._unobserveContentElements(this.domApi.childNodes)},_hasListeners:function(){return!!this._listeners.length},_scheduleNotify:function(){this._debouncer&&this._debouncer.stop();this._debouncer=Polymer.Debounce(this._debouncer,this._notify);this._debouncer.context=this;Polymer.dom.addDebouncer(this._debouncer)},notify:function(){this._hasListeners()&&this._scheduleNotify()},_notify:function(){this._beforeCallListeners();
    this._callListeners()},_beforeCallListeners:function(){this._updateContentElements()},_updateContentElements:function(){this._observeContentElements(this.domApi.childNodes)},_observeContentElements:function(e){for(var g=0,h;g<e.length&&(h=e[g]);g++)this._isContent(h)&&(h.__observeNodesMap=h.__observeNodesMap||new WeakMap,h.__observeNodesMap.has(this)||h.__observeNodesMap.set(this,this._observeContent(h)))},_observeContent:function(e){var g=this;e=Polymer.dom(e).observeNodes(function(){g._scheduleNotify()});
    e._avoidChangeCalculation=!0;return e},_unobserveContentElements:function(e){for(var g=0,h,k;g<e.length&&(h=e[g]);g++)this._isContent(h)&&(k=h.__observeNodesMap&&h.__observeNodesMap.get(this))&&(Polymer.dom(h).unobserveNodes(k),h.__observeNodesMap.delete(this))},_isContent:function(e){return"content"===e.localName},_callListeners:function(){for(var e=this._listeners,g=this._getEffectiveNodes(),h=0,k;h<e.length&&(k=e[h]);h++){var l=this._generateListenerInfo(k,g);(l||k._alwaysNotify)&&this._callListener(k,
    l)}},_getEffectiveNodes:function(){return this.domApi.getEffectiveChildNodes()},_generateListenerInfo:function(e,g){if(e._avoidChangeCalculation)return!0;for(var h={target:this.node,addedNodes:[],removedNodes:[]},k=Polymer.ArraySplice.calculateSplices(g,e._nodes),l=0,m;l<k.length&&(m=k[l]);l++)for(var n=0,q;n<m.removed.length&&(q=m.removed[n]);n++)h.removedNodes.push(q);l=0;for(m;l<k.length&&(m=k[l]);l++)for(n=m.index;n<m.index+m.addedCount;n++)h.addedNodes.push(g[n]);e._nodes=g;if(h.addedNodes.length||
    h.removedNodes.length)return h},_callListener:function(e,g){return e.fn.call(this.node,g)},enableShadowAttributeTracking:function(){}};if(b.useShadow){var c=a.EffectiveNodesObserver.prototype._setup,d=a.EffectiveNodesObserver.prototype._cleanup;Polymer.Base.mixin(a.EffectiveNodesObserver.prototype,{_setup:function(){if(!this._observer){var e=this;this._mutationHandler=function(g){g&&g.length&&e._scheduleNotify()};this._observer=new MutationObserver(this._mutationHandler);this._boundFlush=function(){e._flush()};
    Polymer.dom.addStaticFlush(this._boundFlush);this._observer.observe(this.node,{childList:!0})}c.call(this)},_cleanup:function(){this._observer.disconnect();this._mutationHandler=this._observer=null;Polymer.dom.removeStaticFlush(this._boundFlush);d.call(this)},_flush:function(){this._observer&&this._mutationHandler(this._observer.takeRecords())},enableShadowAttributeTracking:function(){if(this._observer){this._makeContentListenersAlwaysNotify();this._observer.disconnect();this._observer.observe(this.node,
    {childList:!0,attributes:!0,subtree:!0});var e=this.domApi.getOwnerRoot();(e=e&&e.host)&&Polymer.dom(e).observer&&Polymer.dom(e).observer.enableShadowAttributeTracking()}},_makeContentListenersAlwaysNotify:function(){for(var e=0,g;e<this._listeners.length;e++)g=this._listeners[e],g._alwaysNotify=g._isContentListener}})}})();
    (function(){var a=Polymer.DomApi.ctor,b=Polymer.Settings;a.DistributedNodesObserver=function(c){a.EffectiveNodesObserver.call(this,c)};a.DistributedNodesObserver.prototype=Object.create(a.EffectiveNodesObserver.prototype);Polymer.Base.mixin(a.DistributedNodesObserver.prototype,{_setup:function(){},_cleanup:function(){},_beforeCallListeners:function(){},_getEffectiveNodes:function(){return this.domApi.getDistributedNodes()}});b.useShadow&&Polymer.Base.mixin(a.DistributedNodesObserver.prototype,{_setup:function(){if(!this._observer){var c=
    this.domApi.getOwnerRoot();if(c=c&&c.host){var d=this;this._observer=Polymer.dom(c).observeNodes(function(){d._scheduleNotify()});this._observer._isContentListener=!0;this._hasAttrSelect()&&Polymer.dom(c).observer.enableShadowAttributeTracking()}}},_hasAttrSelect:function(){var c=this.node.getAttribute("select");return c&&c.match(/[[.]+/)},_cleanup:function(){var c=this.domApi.getOwnerRoot();(c=c&&c.host)&&Polymer.dom(c).unobserveNodes(this._observer);this._observer=null}})})();
    (function(){function a(h,k){k._distributedNodes.push(h);var l=h._destinationInsertionPoints;l?l.push(k):h._destinationInsertionPoints=[k]}function b(h){for(var k=d.Logical.getChildNodes(h),l=0,m;l<k.length;l++)if(m=k[l],m.localName&&"content"===m.localName)return h.domHost}var c=Polymer.DomApi,d=Polymer.TreeApi;Polymer.Base._addFeature({_prepShady:function(){this._useContent=this._useContent||!!this._template},_setupShady:function(){this.shadyRoot=null;this.__domApi||(this.__domApi=null);this.__dom||
    (this.__dom=null);this._ownerShadyRoot||(this._ownerShadyRoot=void 0)},_poolContent:function(){this._useContent&&d.Logical.saveChildNodes(this)},_setupRoot:function(){if(this._useContent&&(this._createLocalRoot(),!this.dataHost)){var h=d.Logical.getChildNodes(this);if(g&&h)for(var k=0;k<h.length;k++)CustomElements.upgrade(h[k])}},_createLocalRoot:function(){this.shadyRoot=this.root;this.shadyRoot._distributionClean=!1;this.shadyRoot._hasDistributed=!1;this.shadyRoot._isShadyRoot=!0;this.shadyRoot._dirtyRoots=
    [];var h=this.shadyRoot._insertionPoints=!this._notes||this._notes._hasContent?this.shadyRoot.querySelectorAll("content"):[];d.Logical.saveChildNodes(this.shadyRoot);for(var k=0,l;k<h.length;k++)l=h[k],d.Logical.saveChildNodes(l),d.Logical.saveChildNodes(l.parentNode);this.shadyRoot.host=this},distributeContent:function(h){if(this.shadyRoot){this.shadyRoot._invalidInsertionPoints=this.shadyRoot._invalidInsertionPoints||h;for(h=this;h&&b(h);)h=h.domHost;Polymer.dom(this)._lazyDistribute(h)}},_distributeContent:function(){this._useContent&&
    !this.shadyRoot._distributionClean&&(this.shadyRoot._invalidInsertionPoints&&(Polymer.dom(this)._updateInsertionPoints(this),this.shadyRoot._invalidInsertionPoints=!1),this._beginDistribute(),this._distributeDirtyRoots(),this._finishDistribute())},_beginDistribute:function(){this._useContent&&c.hasInsertionPoint(this.shadyRoot)&&(this._resetDistribution(),this._distributePool(this.shadyRoot,this._collectPool()))},_distributeDirtyRoots:function(){for(var h=this.shadyRoot._dirtyRoots,k=0,l=h.length,
    m;k<l&&(m=h[k]);k++)m._distributeContent();this.shadyRoot._dirtyRoots=[]},_finishDistribute:function(){if(this._useContent){this.shadyRoot._distributionClean=!0;if(c.hasInsertionPoint(this.shadyRoot)){this._composeTree();for(var h=this.shadyRoot,k=0,l;k<h._insertionPoints.length;k++)l=h._insertionPoints[k],c.hasApi(l)&&Polymer.dom(l).notifyObserver()}else this.shadyRoot._hasDistributed?(h=this._composeNode(this),this._updateChildNodes(this,h)):(d.Composed.clearChildNodes(this),this.appendChild(this.shadyRoot));
    this.shadyRoot._hasDistributed||c.hasApi(this)&&Polymer.dom(this).notifyObserver();this.shadyRoot._hasDistributed=!0}},elementMatches:function(h,k){return c.matchesSelector.call(k||this,h)},_resetDistribution:function(){for(var h=d.Logical.getChildNodes(this),k=0;k<h.length;k++){var l=h[k];l._destinationInsertionPoints&&(l._destinationInsertionPoints=void 0);if("content"==l.localName){var m=l._distributedNodes;if(m)for(var n=0;n<m.length;n++){var q=m[n]._destinationInsertionPoints;q&&q.splice(q.indexOf(l)+
    1,q.length)}}}h=this.shadyRoot._insertionPoints;for(k=0;k<h.length;k++)h[k]._distributedNodes=[]},_collectPool:function(){for(var h=[],k=d.Logical.getChildNodes(this),l=0;l<k.length;l++){var m=k[l];"content"==m.localName?h.push.apply(h,m._distributedNodes):h.push(m)}return h},_distributePool:function(h,k){h=h._insertionPoints;for(var l=0,m=h.length,n;l<m&&(n=h[l]);l++){this._distributeInsertionPoint(n,k);var q=d.Logical.getParentNode(n);q&&q.shadyRoot&&c.hasInsertionPoint(q.shadyRoot)&&q.shadyRoot._distributionClean&&
    (q.shadyRoot._distributionClean=!1,this.shadyRoot._dirtyRoots.push(q))}},_distributeInsertionPoint:function(h,k){for(var l=!1,m=0,n=k.length,q;m<n;m++)(q=k[m])&&this._matchesContentSelect(q,h)&&(a(q,h),k[m]=void 0,l=!0);if(!l)for(k=d.Logical.getChildNodes(h),l=0;l<k.length;l++)a(k[l],h)},_composeTree:function(){this._updateChildNodes(this,this._composeNode(this));for(var h=this.shadyRoot._insertionPoints,k=0,l=h.length,m,n;k<l&&(m=h[k]);k++)n=d.Logical.getParentNode(m),n._useContent||n===this||n===
    this.shadyRoot||this._updateChildNodes(n,this._composeNode(n))},_composeNode:function(h){var k=[];h=d.Logical.getChildNodes(h.shadyRoot||h);for(var l=0;l<h.length;l++){var m=h[l];if("content"==m.localName)for(var n=m._distributedNodes,q=0;q<n.length;q++){var p=n[q],t=p._destinationInsertionPoints;t&&t[t.length-1]===m&&k.push(p)}else k.push(m)}return k},_updateChildNodes:function(h,k){for(var l=d.Composed.getChildNodes(h),m=Polymer.ArraySplice.calculateSplices(k,l),n=0,q=0,p;n<m.length&&(p=m[n]);n++){for(var t=
    0,r;t<p.removed.length&&(r=p.removed[t]);t++)d.Composed.getParentNode(r)===h&&d.Composed.removeChild(h,r),l.splice(p.index+q,1);q-=p.addedCount}for(n=0;n<m.length&&(p=m[n]);n++)for(q=l[p.index],t=p.index,r;t<p.index+p.addedCount;t++)r=k[t],d.Composed.insertBefore(h,r,q),l.splice(t,0,r)},_matchesContentSelect:function(h,k){k=k.getAttribute("select");return k?(k=k.trim())?h instanceof Element&&/^(:not\()?[*.#[a-zA-Z_|]/.test(k)?this.elementMatches(k,h):!1:!0:!0},_elementAdd:function(){},_elementRemove:function(){}});
    var e={get:function(){var h=Polymer.dom(this).getOwnerRoot();return h&&h.host},configurable:!0};Object.defineProperty(Polymer.Base,"domHost",e);Polymer.BaseDescriptors.domHost=e;var g=window.CustomElements&&!CustomElements.useNative})();
    Polymer.Settings.useShadow&&Polymer.Base._addFeature({_poolContent:function(){},_beginDistribute:function(){},distributeContent:function(){},_distributeContent:function(){},_finishDistribute:function(){},_createLocalRoot:function(){this.createShadowRoot();this.shadowRoot.appendChild(this.root);this.root=this.shadowRoot}});
    Polymer.Async={_currVal:0,_lastVal:0,_callbacks:[],_twiddleContent:0,_twiddle:document.createTextNode(""),run:function(a,b){if(0<b)return~setTimeout(a,b);this._twiddle.textContent=this._twiddleContent++;this._callbacks.push(a);return this._currVal++},cancel:function(a){if(0>a)clearTimeout(~a);else{var b=a-this._lastVal;if(0<=b){if(!this._callbacks[b])throw"invalid async handle: "+a;this._callbacks[b]=null}}},_atEndOfMicrotask:function(){for(var a=this._callbacks.length,b=0;b<a;b++){var c=this._callbacks[b];
    if(c)try{c()}catch(d){throw b++,this._callbacks.splice(0,b),this._lastVal+=b,this._twiddle.textContent=this._twiddleContent++,d;}}this._callbacks.splice(0,a);this._lastVal+=a}};(new window.MutationObserver(function(){Polymer.Async._atEndOfMicrotask()})).observe(Polymer.Async._twiddle,{characterData:!0});
    Polymer.Debounce=function(){function a(c){this.context=c;var d=this;this.boundComplete=function(){d.complete()}}var b=Polymer.Async;a.prototype={go:function(c,d){this.finish=function(){b.cancel(e)};var e=b.run(this.boundComplete,d);this.callback=c},stop:function(){this.finish&&(this.finish(),this.callback=this.finish=null)},complete:function(){if(this.finish){var c=this.callback;this.stop();c.call(this.context)}}};return function(c,d,e){c?c.stop():c=new a(this);c.go(d,e);return c}}();
    Polymer.Base._addFeature({_setupDebouncers:function(){this._debouncers={}},debounce:function(a,b,c){return this._debouncers[a]=Polymer.Debounce.call(this,this._debouncers[a],b,c)},isDebouncerActive:function(a){a=this._debouncers[a];return!(!a||!a.finish)},flushDebouncer:function(a){(a=this._debouncers[a])&&a.complete()},cancelDebouncer:function(a){(a=this._debouncers[a])&&a.stop()}});Polymer.DomModule=document.createElement("dom-module");
    Polymer.Base._addFeature({_registerFeatures:function(){this._prepIs();this._prepBehaviors();this._prepConstructor();this._prepTemplate();this._prepShady();this._prepPropertyInfo()},_prepBehavior:function(a){this._addHostAttributes(a.hostAttributes)},_initFeatures:function(){this._registerHost();this._template&&(this._poolContent(),this._beginHosting(),this._stampTemplate(),this._endHosting());this._marshalHostAttributes();this._setupDebouncers();this._marshalBehaviors();this._tryReady()},_marshalBehavior:function(){}});
    