// @license
// Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
// This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
// The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
// The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
// Code distributed by Google as part of the polymer project is also
// subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
// --><!--
// @license
// Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
// This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
// The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
// The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
// Code distributed by Google as part of the polymer project is also
// subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

(function(){Polymer.nar=[];var a=Polymer.Settings.disableUpgradeEnabled;Polymer.Annotations={parseAnnotations:function(b,c){var d=[];this._parseNodeAnnotations(b._content||b.content,d,c||b.hasAttribute("strip-whitespace"));return d},_parseNodeAnnotations:function(b,c,d){return b.nodeType===Node.TEXT_NODE?this._parseTextNodeAnnotation(b,c):this._parseElementAnnotations(b,c,d)},_bindingRegex:/(\[\[|{{)\s*(?:(!)\s*)?((?:[a-zA-Z_$][\w.:$\-*]*)\s*(?:\(\s*(?:(?:(?:(?:[a-zA-Z_$][\w.:$\-*]*)|(?:[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)|(?:(?:'(?:[^'\\]|\\.)*')|(?:"(?:[^"\\]|\\.)*"))\s*)(?:,\s*(?:(?:[a-zA-Z_$][\w.:$\-*]*)|(?:[-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)|(?:(?:'(?:[^'\\]|\\.)*')|(?:"(?:[^"\\]|\\.)*"))\s*))*)?)\)\s*)?)(?:]]|}})/g,
_parseBindings:function(b){for(var c=this._bindingRegex,d=[],e=0,g;null!==(g=c.exec(b));){g.index>e&&d.push({literal:b.slice(e,g.index)});e=g[1][0];var h=!!g[2];g=g[3].trim();var k;if("{"==e&&0<(k=g.indexOf("::"))){var l=g.substring(k+2);g=g.substring(0,k);var m=!0}d.push({compoundIndex:d.length,value:g,mode:e,negate:h,event:l,customEvent:m});e=c.lastIndex}e&&e<b.length&&(b=b.substring(e))&&d.push({literal:b});if(d.length)return d},_literalFromParts:function(b){for(var c="",d=0;d<b.length;d++)c+=
b[d].literal||"";return c},_parseTextNodeAnnotation:function(b,c){var d=this._parseBindings(b.textContent);if(d)return b.textContent=this._literalFromParts(d)||" ",b={bindings:[{kind:"text",name:"textContent",parts:d,isCompound:1!==d.length}]},c.push(b),b},_parseElementAnnotations:function(b,c,d){var e={bindings:[],events:[]};"content"===b.localName&&(c._hasContent=!0);this._parseChildNodesAnnotations(b,e,c,d);b.attributes&&(this._parseNodeAttributeAnnotations(b,e,c),this.prepElement&&this.prepElement(b));
(e.bindings.length||e.events.length||e.id)&&c.push(e);return e},_parseChildNodesAnnotations:function(b,c,d,e){if(b.firstChild)for(var g=b.firstChild,h=0;g;){var k=g.nextSibling;"template"!==g.localName||g.hasAttribute("preserve-content")||this._parseTemplate(g,h,d,c,e);"slot"==g.localName&&(g=this._replaceSlotWithContent(g));if(g.nodeType===Node.TEXT_NODE){for(var l=k;l&&l.nodeType===Node.TEXT_NODE;)g.textContent+=l.textContent,k=l.nextSibling,b.removeChild(l),l=k;e&&!g.textContent.trim()&&(b.removeChild(g),
h--)}g.parentNode&&(g=this._parseNodeAnnotations(g,d,e))&&(g.parent=c,g.index=h);g=k;h++}},_replaceSlotWithContent:function(b){for(var c=b.ownerDocument.createElement("content");b.firstChild;)c.appendChild(b.firstChild);for(var d=b.attributes,e=0;e<d.length;e++){var g=d[e];c.setAttribute(g.name,g.value)}(d=b.getAttribute("name"))&&c.setAttribute("select","[slot\x3d'"+d+"']");b.parentNode.replaceChild(c,b);return c},_parseTemplate:function(b,c,d,e,g){var h=document.createDocumentFragment();h._notes=
this.parseAnnotations(b,g);h.appendChild(b.content);d.push({bindings:Polymer.nar,events:Polymer.nar,templateContent:h,parent:e,index:c})},_parseNodeAttributeAnnotations:function(b,c){for(var d=Array.prototype.slice.call(b.attributes),e=d.length-1,g;g=d[e];e--){var h=g.name;g=g.value;var k;"on-"===h.slice(0,3)?(b.removeAttribute(h),c.events.push({name:h.slice(3),value:g})):(k=this._parseNodeAttributeAnnotation(b,h,g))?c.bindings.push(k):"id"===h&&(c.id=g)}},_parseNodeAttributeAnnotation:function(b,
c,d){if(d=this._parseBindings(d)){var e=c,g="property";"$"==c[c.length-1]&&(c=c.slice(0,-1),g="attribute");var h=this._literalFromParts(d);h&&"attribute"==g&&b.setAttribute(c,h);"input"===b.localName&&"value"===e&&b.setAttribute(e,"");a&&"disable-upgrade$"===e&&b.setAttribute(c,"");b.removeAttribute(e);b=Polymer.CaseMap.dashToCamelCase(c);"property"===g&&(c=b);return{kind:g,name:c,propertyName:b,parts:d,literal:h,isCompound:1!==d.length}}},findAnnotatedNode:function(b,c){var d=c.parent&&Polymer.Annotations.findAnnotatedNode(b,
c.parent);if(d)for(b=d.firstChild,d=0;b;b=b.nextSibling){if(c.index===d++)return b}else return b}}})();Polymer.Path={root:function(a){var b=a.indexOf(".");return-1===b?a:a.slice(0,b)},isDeep:function(a){return-1!==a.indexOf(".")},isAncestor:function(a,b){return 0===a.indexOf(b+".")},isDescendant:function(a,b){return 0===b.indexOf(a+".")},translate:function(a,b,c){return b+c.slice(a.length)},matches:function(a,b,c){return a===c||this.isAncestor(a,c)||!!b&&this.isDescendant(a,c)}};
Polymer.Base._addFeature({_prepAnnotations:function(){if(this._template){var a=this;Polymer.Annotations.prepElement=function(b){a._prepElement(b)};this._template._content&&this._template._content._notes?this._notes=this._template._content._notes:(this._notes=Polymer.Annotations.parseAnnotations(this._template),this._processAnnotations(this._notes));Polymer.Annotations.prepElement=null}else this._notes=[]},_processAnnotations:function(a){for(var b=0;b<a.length;b++){for(var c=a[b],d=0;d<c.bindings.length;d++)for(var e=
c.bindings[d],g=0;g<e.parts.length;g++){var h=e.parts[g];if(!h.literal){var k=this._parseMethod(h.value);k?h.signature=k:h.model=Polymer.Path.root(h.value)}}if(c.templateContent){this._processAnnotations(c.templateContent._notes);e=c.templateContent._parentProps=this._discoverTemplateParentProps(c.templateContent._notes);d=[];for(var l in e)e="_parent_"+l,d.push({index:c.index,kind:"property",name:e,propertyName:e,parts:[{mode:"{",model:l,value:l}]});c.bindings=c.bindings.concat(d)}}},_discoverTemplateParentProps:function(a){for(var b=
{},c=0,d;c<a.length&&(d=a[c]);c++){for(var e=0,g=d.bindings,h;e<g.length&&(h=g[e]);e++)for(var k=0,l=h.parts,m;k<l.length&&(m=l[k]);k++)if(m.signature){for(var n=m.signature.args,q=0;q<n.length;q++){var p=n[q].model;p&&(b[p]=!0)}m.signature.dynamicFn&&(b[m.signature.method]=!0)}else m.model&&(b[m.model]=!0);d.templateContent&&Polymer.Base.mixin(b,d.templateContent._parentProps)}return b},_prepElement:function(a){Polymer.ResolveUrl.resolveAttrs(a,this._template.ownerDocument)},_findAnnotatedNode:Polymer.Annotations.findAnnotatedNode,
_marshalAnnotationReferences:function(){this._template&&(this._marshalIdNodes(),this._marshalAnnotatedNodes(),this._marshalAnnotatedListeners())},_configureAnnotationReferences:function(){for(var a=this._notes,b=this._nodes,c=0;c<a.length;c++){var d=a[c],e=b[c];this._configureTemplateContent(d,e);this._configureCompoundBindings(d,e)}},_configureTemplateContent:function(a,b){a.templateContent&&(b._content=a.templateContent)},_configureCompoundBindings:function(a,b){a=a.bindings;for(var c=0;c<a.length;c++){var d=
a[c];if(d.isCompound){for(var e=b.__compoundStorage__||(b.__compoundStorage__={}),g=d.parts,h=Array(g.length),k=0;k<g.length;k++)h[k]=g[k].literal;g=d.name;e[g]=h;d.literal&&"property"==d.kind&&(b._configValue?b._configValue(g,d.literal):b[g]=d.literal)}}},_marshalIdNodes:function(){this.$={};for(var a=0,b=this._notes.length,c;a<b&&(c=this._notes[a]);a++)c.id&&(this.$[c.id]=this._findAnnotatedNode(this.root,c))},_marshalAnnotatedNodes:function(){if(this._notes&&this._notes.length){for(var a=Array(this._notes.length),
b=0;b<this._notes.length;b++)a[b]=this._findAnnotatedNode(this.root,this._notes[b]);this._nodes=a}},_marshalAnnotatedListeners:function(){for(var a=0,b=this._notes.length,c;a<b&&(c=this._notes[a]);a++)if(c.events&&c.events.length)for(var d=this._findAnnotatedNode(this.root,c),e=0,g=c.events,h;e<g.length&&(h=g[e]);e++)this.listen(d,h.name,h.value)}});
Polymer.Base._addFeature({listeners:{},_listenListeners:function(a){var b;for(b in a){if(0>b.indexOf(".")){var c=this;var d=b}else d=b.split("."),c=this.$[d[0]],d=d[1];this.listen(c,d,a[b])}},listen:function(a,b,c){var d=this._recallEventHandler(this,b,a,c);d||(d=this._createEventHandler(a,b,c));d._listening||(this._listen(a,b,d),d._listening=!0)},_boundListenerKey:function(a,b){return a+":"+b},_recordEventHandler:function(a,b,c,d,e){var g=a.__boundListeners;g||(g=a.__boundListeners=new WeakMap);
a=g.get(c);a||(a={},Polymer.Settings.isIE&&c==window||g.set(c,a));a[this._boundListenerKey(b,d)]=e},_recallEventHandler:function(a,b,c,d){if(a=a.__boundListeners)if(c=a.get(c))return c[this._boundListenerKey(b,d)]},_createEventHandler:function(a,b,c){function d(g){if(e[c])e[c](g,g.detail);else e._warn(e._logf("_createEventHandler","listener method `"+c+"` not defined"))}var e=this;d._listening=!1;this._recordEventHandler(e,b,a,c,d);return d},unlisten:function(a,b,c){if(c=this._recallEventHandler(this,
b,a,c))this._unlisten(a,b,c),c._listening=!1},_listen:function(a,b,c){a.addEventListener(b,c)},_unlisten:function(a,b,c){a.removeEventListener(b,c)}});
(function(){function a(u){var w=u.sourceCapabilities;if(!w||w.firesTouchEvents)if(u.__polymerGesturesHandled={skip:!0},"click"===u.type){if(w=Polymer.dom(u).path)for(var x=0;x<w.length;x++)if(w[x]===t.mouse.target)return;u.preventDefault();u.stopPropagation()}}function b(u){if(!(-1<l.indexOf(u))&&"touchend"!==u&&k&&q&&Polymer.Settings.passiveTouchGestures)return{passive:!0}}function c(u){for(var w=p?["click"]:l,x=0,A;x<w.length;x++)A=w[x],u?document.addEventListener(A,a,!0):document.removeEventListener(A,
a,!0)}function d(u){var w=u.type;return-1<l.indexOf(w)?"mousemove"===w?(w=void 0===u.buttons?1:u.buttons,u instanceof window.MouseEvent&&!n&&(w=m[u.which]||0),!!(w&1)):0===(void 0===u.button?0:u.button):!1}function e(u,w,x){u.movefn=w;u.upfn=x;document.addEventListener("mousemove",w);document.addEventListener("mouseup",x)}function g(u){document.removeEventListener("mousemove",u.movefn);document.removeEventListener("mouseup",u.upfn);u.movefn=null;u.upfn=null}var h=Polymer.DomApi.wrap,k="string"===
typeof document.head.style.touchAction,l=["mousedown","mousemove","mouseup","click"],m=[0,1,4,2];try{var n=1===(new MouseEvent("test",{buttons:1})).buttons}catch(u){n=!1}var q=!1;(function(){try{var u=Object.defineProperty({},"passive",{get:function(){q=!0}});window.addEventListener("test",null,u);window.removeEventListener("test",null,u)}catch(w){}})();var p=navigator.userAgent.match(/iP(?:[oa]d|hone)|Android/),t={mouse:{target:null,mouseIgnoreJob:null},touch:{x:0,y:0,id:-1,scrollDecided:!1}};document.addEventListener("touchend",
function(u){t.mouse.mouseIgnoreJob||c(!0);t.mouse.target=Polymer.dom(u).rootTarget;t.mouse.mouseIgnoreJob=Polymer.Debounce(t.mouse.mouseIgnoreJob,function(){c();t.mouse.target=null;t.mouse.mouseIgnoreJob=null},2500)},q?{passive:!0}:!1);var r={gestures:{},recognizers:[],deepTargetFind:function(u,w){for(var x=document.elementFromPoint(u,w),A=x;A&&A.shadowRoot;)(A=A.shadowRoot.elementFromPoint(u,w))&&(x=A);return x},findOriginalTarget:function(u){return u.path?u.path[0]:u.target},handleNative:function(u){var w=
u.type,x=h(u.currentTarget).__polymerGestures;if(x&&(x=x[w])){if(!u.__polymerGesturesHandled&&(u.__polymerGesturesHandled={},"touch"===w.slice(0,5))){var A=u.changedTouches[0];"touchstart"===w&&1===u.touches.length&&(t.touch.id=A.identifier);if(t.touch.id!==A.identifier)return;k||("touchstart"===w||"touchmove"===w)&&r.handleTouchAction(u)}A=u.__polymerGesturesHandled;if(!A.skip){for(var y=r.recognizers,B=0,F;B<y.length;B++)F=y[B],x[F.name]&&!A[F.name]&&F.flow&&-1<F.flow.start.indexOf(u.type)&&F.reset&&
F.reset();B=0;for(F;B<y.length;B++)F=y[B],x[F.name]&&!A[F.name]&&(A[F.name]=!0,F[w](u))}}},handleTouchAction:function(u){var w=u.changedTouches[0],x=u.type;if("touchstart"===x)t.touch.x=w.clientX,t.touch.y=w.clientY,t.touch.scrollDecided=!1;else if("touchmove"===x&&!t.touch.scrollDecided){t.touch.scrollDecided=!0;x=Polymer.dom(u).path;for(var A="auto",y=0,B;y<x.length;y++)if(B=x[y],B.__polymerGesturesTouchAction){A=B.__polymerGesturesTouchAction;break}x=A;A=!1;y=Math.abs(t.touch.x-w.clientX);w=Math.abs(t.touch.y-
w.clientY);u.cancelable&&("none"===x?A=!0:"pan-x"===x?A=w>y:"pan-y"===x&&(A=y>w));A?u.preventDefault():r.prevent("track")}},add:function(u,w,x){u=h(u);var A=this.gestures[w],y=A.deps,B=A.name,F=u.__polymerGestures;F||(u.__polymerGestures=F={});for(var K=0,L,N;K<y.length;K++)L=y[K],p&&-1<l.indexOf(L)&&"click"!==L||((N=F[L])||(F[L]=N={_count:0}),0===N._count&&u.addEventListener(L,this.handleNative,b(L)),N[B]=(N[B]||0)+1,N._count=(N._count||0)+1);u.addEventListener(w,x);A.touchAction&&this.setTouchAction(u,
A.touchAction)},remove:function(u,w,x){u=h(u);var A=this.gestures[w],y=A.deps;A=A.name;var B=u.__polymerGestures;if(B)for(var F=0,K,L;F<y.length;F++)K=y[F],(L=B[K])&&L[A]&&(L[A]=(L[A]||1)-1,L._count=(L._count||1)-1,0===L._count&&u.removeEventListener(K,this.handleNative,b(K)));u.removeEventListener(w,x)},register:function(u){this.recognizers.push(u);for(var w=0;w<u.emits.length;w++)this.gestures[u.emits[w]]=u},findRecognizerByEvent:function(u){for(var w=0,x;w<this.recognizers.length;w++){x=this.recognizers[w];
for(var A=0,y;A<x.emits.length;A++)if(y=x.emits[A],y===u)return x}return null},setTouchAction:function(u,w){k&&(u.style.touchAction=w);u.__polymerGesturesTouchAction=w},fire:function(u,w,x){Polymer.Base.fire(w,x,{node:u,bubbles:!0,cancelable:!0}).defaultPrevented&&(u=x.preventer||x.sourceEvent)&&u.preventDefault&&u.preventDefault()},prevent:function(u){u=this.findRecognizerByEvent(u);u.info&&(u.info.prevent=!0)},resetMouseCanceller:function(){t.mouse.mouseIgnoreJob&&t.mouse.mouseIgnoreJob.complete()}};
r.register({name:"downup",deps:["mousedown","touchstart","touchend"],flow:{start:["mousedown","touchstart"],end:["mouseup","touchend"]},emits:["down","up"],info:{movefn:null,upfn:null},reset:function(){g(this.info)},mousedown:function(u){if(d(u)){var w=r.findOriginalTarget(u),x=this;e(this.info,function(A){d(A)||(x.fire("up",w,A),g(x.info))},function(A){d(A)&&x.fire("up",w,A);g(x.info)});this.fire("down",w,u)}},touchstart:function(u){this.fire("down",r.findOriginalTarget(u),u.changedTouches[0],u)},
touchend:function(u){this.fire("up",r.findOriginalTarget(u),u.changedTouches[0],u)},fire:function(u,w,x,A){r.fire(w,u,{x:x.clientX,y:x.clientY,sourceEvent:x,preventer:A,prevent:function(y){return r.prevent(y)}})}});r.register({name:"track",touchAction:"none",deps:["mousedown","touchstart","touchmove","touchend"],flow:{start:["mousedown","touchstart"],end:["mouseup","touchend"]},emits:["track"],info:{x:0,y:0,state:"start",started:!1,moves:[],addMove:function(u){2<this.moves.length&&this.moves.shift();
this.moves.push(u)},movefn:null,upfn:null,prevent:!1},reset:function(){this.info.state="start";this.info.started=!1;this.info.moves=[];this.info.x=0;this.info.y=0;this.info.prevent=!1;g(this.info)},hasMovedEnough:function(u,w){if(this.info.prevent)return!1;if(this.info.started)return!0;w=Math.abs(this.info.y-w);return 5<=Math.abs(this.info.x-u)||5<=w},mousedown:function(u){if(d(u)){var w=r.findOriginalTarget(u),x=this,A=function(y){var B=y.clientX,F=y.clientY;x.hasMovedEnough(B,F)&&(x.info.state=
x.info.started?"mouseup"===y.type?"end":"track":"start","start"===x.info.state&&r.prevent("tap"),x.info.addMove({x:B,y:F}),d(y)||(x.info.state="end",g(x.info)),x.fire(w,y),x.info.started=!0)};e(this.info,A,function(y){x.info.started&&A(y);g(x.info)});this.info.x=u.clientX;this.info.y=u.clientY}},touchstart:function(u){u=u.changedTouches[0];this.info.x=u.clientX;this.info.y=u.clientY},touchmove:function(u){var w=r.findOriginalTarget(u);u=u.changedTouches[0];var x=u.clientX,A=u.clientY;this.hasMovedEnough(x,
A)&&("start"===this.info.state&&r.prevent("tap"),this.info.addMove({x:x,y:A}),this.fire(w,u),this.info.state="track",this.info.started=!0)},touchend:function(u){var w=r.findOriginalTarget(u),x=u.changedTouches[0];this.info.started&&(this.info.state="end",this.info.addMove({x:x.clientX,y:x.clientY}),this.fire(w,x,u))},fire:function(u,w,x){var A=this.info.moves[this.info.moves.length-2],y=this.info.moves[this.info.moves.length-1],B=y.x-this.info.x,F=y.y-this.info.y,K=0;if(A){var L=y.x-A.x;K=y.y-A.y}return r.fire(u,
"track",{state:this.info.state,x:w.clientX,y:w.clientY,dx:B,dy:F,ddx:L,ddy:K,sourceEvent:w,preventer:x,hover:function(){return r.deepTargetFind(w.clientX,w.clientY)}})}});r.register({name:"tap",deps:["mousedown","click","touchstart","touchend"],flow:{start:["mousedown","touchstart"],end:["click","touchend"]},emits:["tap"],info:{x:NaN,y:NaN,prevent:!1},reset:function(){this.info.x=NaN;this.info.y=NaN;this.info.prevent=!1},save:function(u){this.info.x=u.clientX;this.info.y=u.clientY},mousedown:function(u){d(u)&&
this.save(u)},click:function(u){d(u)&&this.forward(u)},touchstart:function(u){this.save(u.changedTouches[0],u)},touchend:function(u){this.forward(u.changedTouches[0],u)},forward:function(u,w){var x=Math.abs(u.clientX-this.info.x),A=Math.abs(u.clientY-this.info.y),y=r.findOriginalTarget(u);if(!(x=isNaN(x)||isNaN(A)||25>=x&&25>=A))if("click"===u.type)if(0===u.detail)x=!0;else{x=r.findOriginalTarget(u).getBoundingClientRect();A=u.pageX;var B=u.pageY;x=!(A>=x.left&&A<=x.right&&B>=x.top&&B<=x.bottom)}else x=
!1;x&&(this.info.prevent||r.fire(y,"tap",{x:u.clientX,y:u.clientY,sourceEvent:u,preventer:w}))}});var v={x:"pan-x",y:"pan-y",none:"none",all:"auto"};Polymer.Base._addFeature({_setupGestures:function(){this.__polymerGestures=null},_listen:function(u,w,x){r.gestures[w]?r.add(u,w,x):u.addEventListener(w,x)},_unlisten:function(u,w,x){r.gestures[w]?r.remove(u,w,x):u.removeEventListener(w,x)},setScrollDirection:function(u,w){r.setTouchAction(w||this,v[u]||"auto")}});Polymer.Gestures=r})();
(function(){Polymer.Base._addFeature({$$:function(b){return Polymer.dom(this.root).querySelector(b)},toggleClass:function(b,c,d){d=d||this;1==arguments.length&&(c=!d.classList.contains(b));c?Polymer.dom(d).classList.add(b):Polymer.dom(d).classList.remove(b)},toggleAttribute:function(b,c,d){d=d||this;1==arguments.length&&(c=!d.hasAttribute(b));c?Polymer.dom(d).setAttribute(b,""):Polymer.dom(d).removeAttribute(b)},classFollows:function(b,c,d){d&&Polymer.dom(d).classList.remove(b);c&&Polymer.dom(c).classList.add(b)},
attributeFollows:function(b,c,d){d&&Polymer.dom(d).removeAttribute(b);c&&Polymer.dom(c).setAttribute(b,"")},getEffectiveChildNodes:function(){return Polymer.dom(this).getEffectiveChildNodes()},getEffectiveChildren:function(){return Polymer.dom(this).getEffectiveChildNodes().filter(function(b){return b.nodeType===Node.ELEMENT_NODE})},getEffectiveTextContent:function(){for(var b=this.getEffectiveChildNodes(),c=[],d=0,e;e=b[d];d++)e.nodeType!==Node.COMMENT_NODE&&c.push(Polymer.dom(e).textContent);return c.join("")},
queryEffectiveChildren:function(b){return(b=Polymer.dom(this).queryDistributedElements(b))&&b[0]},queryAllEffectiveChildren:function(b){return Polymer.dom(this).queryDistributedElements(b)},getContentChildNodes:function(b){return(b=Polymer.dom(this.root).querySelector(b||"content"))?Polymer.dom(b).getDistributedNodes():[]},getContentChildren:function(b){return this.getContentChildNodes(b).filter(function(c){return c.nodeType===Node.ELEMENT_NODE})},fire:function(b,c,d){d=d||Polymer.nob;var e=d.node||
this;c=null===c||void 0===c?{}:c;var g=d._useCache;d=this._getEvent(b,void 0===d.bubbles?!0:d.bubbles,!!d.cancelable,g);d.detail=c;g&&(this.__eventCache[b]=null);e.dispatchEvent(d);g&&(this.__eventCache[b]=d);return d},__eventCache:{},_getEvent:function(b,c,d,e){(e=e&&this.__eventCache[b])&&e.bubbles==c&&e.cancelable==d||(e=new Event(b,{bubbles:!!c,cancelable:d}));return e},async:function(b,c){var d=this;return Polymer.Async.run(function(){b.call(d)},c)},cancelAsync:function(b){Polymer.Async.cancel(b)},
arrayDelete:function(b,c){if(Array.isArray(b)){if(c=b.indexOf(c),0<=c)return b.splice(c,1)}else if(c=this._get(b).indexOf(c),0<=c)return this.splice(b,c,1)},transform:function(b,c){c=c||this;c.style.webkitTransform=b;c.style.transform=b},translate3d:function(b,c,d,e){this.transform("translate3d("+b+","+c+","+d+")",e||this)},importHref:function(b,c,d,e){function g(q){q.target.__firedError=!0;q.target.removeEventListener("load",h);q.target.removeEventListener("error",g);return d.call(n,q)}function h(q){q.target.__firedLoad=
!0;q.target.removeEventListener("load",h);q.target.removeEventListener("error",g);return c.call(n,q)}var k=document.createElement("link");k.rel="import";k.href=b;b=Polymer.Base.importHref.imported=Polymer.Base.importHref.imported||{};var l=b[k.href],m=l||k,n=this;c&&m.addEventListener("load",h);d&&m.addEventListener("error",g);l?(l.__firedLoad&&l.dispatchEvent(new Event("load")),l.__firedError&&l.dispatchEvent(new Event("error"))):(b[k.href]=k,e&&k.setAttribute("async",""),document.head.appendChild(k));
return m},create:function(b,c){b=document.createElement(b);if(c)for(var d in c)b[d]=c[d];return b},isLightDescendant:function(b){return this!==b&&this.contains(b)&&Polymer.dom(this).getOwnerRoot()===Polymer.dom(b).getOwnerRoot()},isLocalDescendant:function(b){return this.root===Polymer.dom(b).getOwnerRoot()}});if(!Polymer.Settings.useNativeCustomElements){var a=Polymer.Base.importHref;Polymer.Base.importHref=function(b,c,d,e){CustomElements.ready=!1;return a.call(this,b,function(g){CustomElements.upgradeDocumentTree(document);
CustomElements.ready=!0;if(c)return c.call(this,g)},d,e)}}})();
Polymer.Bind={prepareModel:function(a){Polymer.Base.mixin(a,this._modelApi)},_modelApi:{_notifyChange:function(a,b,c){c=void 0===c?this[a]:c;b=b||Polymer.CaseMap.camelToDashCase(a)+"-changed";this.fire(b,{value:c},{bubbles:!1,cancelable:!1,_useCache:Polymer.Settings.eventDataCache||!Polymer.Settings.isIE})},_propertySetter:function(a,b,c,d){var e=this.__data__[a];e===b||e!==e&&b!==b||(this.__data__[a]=b,"object"==typeof b&&this._clearPath(a),this._propertyChanged&&this._propertyChanged(a,b,e),c&&
this._effectEffects(a,b,c,e,d));return e},__setProperty:function(a,b,c,d){d=d||this;var e=d._propertyEffects&&d._propertyEffects[a];e?d._propertySetter(a,b,e,c):d[a]!==b&&(d[a]=b)},_effectEffects:function(a,b,c,d,e){b=0;for(var g=c.length,h;b<g&&(h=c[b]);b++)h.fn.call(this,a,this[a],h.effect,d,e)},_clearPath:function(a){for(var b in this.__data__)Polymer.Path.isDescendant(a,b)&&(this.__data__[b]=void 0)}},ensurePropertyEffects:function(a,b){a._propertyEffects||(a._propertyEffects={});var c=a._propertyEffects[b];
c||(c=a._propertyEffects[b]=[]);return c},addPropertyEffect:function(a,b,c,d){a=this.ensurePropertyEffects(a,b);c={kind:c,effect:d,fn:Polymer.Bind["_"+c+"Effect"]};a.push(c);return c},createBindings:function(a){var b=a._propertyEffects;if(b)for(var c in b){var d=b[c];d.sort(this._sortPropertyEffects);this._createAccessors(a,c,d)}},_sortPropertyEffects:function(){var a={compute:0,annotation:1,annotatedComputation:2,reflect:3,notify:4,observer:5,complexObserver:6,"function":7};return function(b,c){return a[b.kind]-
a[c.kind]}}(),_createAccessors:function(a,b,c){function d(h){this._propertySetter(b,h,c)}var e={get:function(){return this.__data__[b]}},g=a.getPropertyInfo&&a.getPropertyInfo(b);g&&g.readOnly?g.computed||(a["_set"+this.upper(b)]=d):e.set=d;Object.defineProperty(a,b,e)},upper:function(a){return a[0].toUpperCase()+a.substring(1)},_addAnnotatedListener:function(a,b,c,d,e,g){a._bindListeners||(a._bindListeners=[]);g=this._notedListenerFactory(c,d,Polymer.Path.isDeep(d),g);e=e||Polymer.CaseMap.camelToDashCase(c)+
"-changed";a._bindListeners.push({index:b,property:c,path:d,changedFn:g,event:e})},_isEventBogus:function(a,b){return a.path&&a.path[0]!==b},_notedListenerFactory:function(a,b,c,d){return function(e,g,h){h?(e=Polymer.Path.translate(a,b,h),this._notifyPath(e,g)):(g=e[a],d&&(g=!g),c?this.__data__[b]!=g&&this.set(b,g):this[b]=g)}},prepareInstance:function(a){a.__data__=Object.create(null)},setupBindListeners:function(a){for(var b=a._bindListeners,c=0,d=b.length,e;c<d&&(e=b[c]);c++)this._addNotifyListener(a._nodes[e.index],
a,e.event,e.changedFn)},_addNotifyListener:function(a,b,c,d){a.addEventListener(c,function(e){return b._notifyListener(d,e)})}};
Polymer.Base.mixin(Polymer.Bind,{_shouldAddListener:function(a){return a.name&&"attribute"!=a.kind&&"text"!=a.kind&&!a.isCompound&&"{"===a.parts[0].mode},_annotationEffect:function(a,b,c){a!=c.value&&(b=this._get(c.value),this.__data__[c.value]=b);this._applyEffectValue(c,b)},_reflectEffect:function(a,b,c){this.reflectPropertyToAttribute(a,c.attribute,b)},_notifyEffect:function(a,b,c,d,e){e||this._notifyChange(a,c.event,b)},_functionEffect:function(a,b,c,d,e){c.call(this,a,b,d,e)},_observerEffect:function(a,
b,c,d){(a=this[c.method])?a.call(this,b,d):this._warn(this._logf("_observerEffect","observer method `"+c.method+"` not defined"))},_complexObserverEffect:function(a,b,c){var d=this[c.method];d?(a=Polymer.Bind._marshalArgs(this.__data__,c,a,b))&&d.apply(this,a):c.dynamicFn||this._warn(this._logf("_complexObserverEffect","observer method `"+c.method+"` not defined"))},_computeEffect:function(a,b,c){var d=this[c.method];if(d){if(a=Polymer.Bind._marshalArgs(this.__data__,c,a,b))d=d.apply(this,a),this.__setProperty(c.name,
d)}else c.dynamicFn||this._warn(this._logf("_computeEffect","compute method `"+c.method+"` not defined"))},_annotatedComputationEffect:function(a,b,c){var d=this._rootDataHost||this,e=d[c.method];if(e){if(a=Polymer.Bind._marshalArgs(this.__data__,c,a,b))d=e.apply(d,a),this._applyEffectValue(c,d)}else c.dynamicFn||d._warn(d._logf("_annotatedComputationEffect","compute method `"+c.method+"` not defined"))},_marshalArgs:function(a,b,c,d){var e=[],g=b.args;b=1<g.length||b.dynamicFn;for(var h=0,k=g.length;h<
k;h++){var l=g[h],m=l.name;if(l.literal)var n=l.value;else c===m?n=d:(n=a[m],void 0===n&&l.structured&&(n=Polymer.Base._get(m,a)));if(b&&void 0===n)return;l.wildcard?(l=Polymer.Path.isAncestor(c,m),e[h]={path:l?c:m,value:l?d:n,base:n}):e[h]=n}return e}});
Polymer.Base._addFeature({_addPropertyEffect:function(a,b,c){a=Polymer.Bind.addPropertyEffect(this,a,b,c);a.pathFn=this["_"+a.kind+"PathEffect"]},_prepEffects:function(){Polymer.Bind.prepareModel(this);this._addAnnotationEffects(this._notes)},_prepBindings:function(){Polymer.Bind.createBindings(this)},_addPropertyEffects:function(a){if(a)for(var b in a){var c=a[b];c.observer&&this._addObserverEffect(b,c.observer);c.computed&&(c.readOnly=!0,this._addComputedEffect(b,c.computed));c.notify&&this._addPropertyEffect(b,
"notify",{event:Polymer.CaseMap.camelToDashCase(b)+"-changed"});if(c.reflectToAttribute){var d=Polymer.CaseMap.camelToDashCase(b);"-"===d[0]?this._warn(this._logf("_addPropertyEffects","Property "+b+" cannot be reflected to attribute "+d+' because "-" is not a valid starting attribute name. Use a lowercase first letter for the property instead.')):this._addPropertyEffect(b,"reflect",{attribute:d})}c.readOnly&&Polymer.Bind.ensurePropertyEffects(this,b)}},_addComputedEffect:function(a,b){b=this._parseMethod(b);
for(var c=b.dynamicFn,d=0,e;d<b.args.length&&(e=b.args[d]);d++)this._addPropertyEffect(e.model,"compute",{method:b.method,args:b.args,trigger:e,name:a,dynamicFn:c});c&&this._addPropertyEffect(b.method,"compute",{method:b.method,args:b.args,trigger:null,name:a,dynamicFn:c})},_addObserverEffect:function(a,b){this._addPropertyEffect(a,"observer",{method:b,property:a})},_addComplexObserverEffects:function(a){if(a)for(var b=0,c;b<a.length&&(c=a[b]);b++)this._addComplexObserverEffect(c)},_addComplexObserverEffect:function(a){var b=
this._parseMethod(a);if(!b)throw Error("Malformed observer expression '"+a+"'");a=b.dynamicFn;for(var c=0,d;c<b.args.length&&(d=b.args[c]);c++)this._addPropertyEffect(d.model,"complexObserver",{method:b.method,args:b.args,trigger:d,dynamicFn:a});a&&this._addPropertyEffect(b.method,"complexObserver",{method:b.method,args:b.args,trigger:null,dynamicFn:a})},_addAnnotationEffects:function(a){for(var b=0,c;b<a.length&&(c=a[b]);b++)for(var d=c.bindings,e=0,g;e<d.length&&(g=d[e]);e++)this._addAnnotationEffect(g,
b)},_addAnnotationEffect:function(a,b){Polymer.Bind._shouldAddListener(a)&&Polymer.Bind._addAnnotatedListener(this,b,a.name,a.parts[0].value,a.parts[0].event,a.parts[0].negate);for(var c=0;c<a.parts.length;c++){var d=a.parts[c];d.signature?this._addAnnotatedComputationEffect(a,d,b):d.literal||("attribute"===a.kind&&"-"===a.name[0]?this._warn(this._logf("_addAnnotationEffect","Cannot set attribute "+a.name+' because "-" is not a valid attribute starting character')):this._addPropertyEffect(d.model,
"annotation",{kind:a.kind,index:b,name:a.name,propertyName:a.propertyName,value:d.value,isCompound:a.isCompound,compoundIndex:d.compoundIndex,event:d.event,customEvent:d.customEvent,negate:d.negate}))}},_addAnnotatedComputationEffect:function(a,b,c){var d=b.signature;if(d.static)this.__addAnnotatedComputationEffect("__static__",c,a,b,null);else{for(var e=0,g;e<d.args.length&&(g=d.args[e]);e++)g.literal||this.__addAnnotatedComputationEffect(g.model,c,a,b,g);d.dynamicFn&&this.__addAnnotatedComputationEffect(d.method,
c,a,b,null)}},__addAnnotatedComputationEffect:function(a,b,c,d,e){this._addPropertyEffect(a,"annotatedComputation",{index:b,isCompound:c.isCompound,compoundIndex:d.compoundIndex,kind:c.kind,name:c.name,negate:d.negate,method:d.signature.method,args:d.signature.args,trigger:e,dynamicFn:d.signature.dynamicFn})},_parseMethod:function(a){var b=a.match(/([^\s]+?)\(([\s\S]*)\)/);if(b){a={method:b[1],static:!0};this.getPropertyInfo(a.method)!==Polymer.nob&&(a.static=!1,a.dynamicFn=!0);if(b[2].trim())return b=
b[2].replace(/\\,/g,"\x26comma;").split(","),this._parseArgs(b,a);a.args=Polymer.nar;return a}},_parseArgs:function(a,b){b.args=a.map(function(c){c=this._parseArg(c);c.literal||(b.static=!1);return c},this);return b},_parseArg:function(a){a=a.trim().replace(/&comma;/g,",").replace(/\\(.)/g,"$1");var b={name:a},c=a[0];"-"===c&&(c=a[1]);"0"<=c&&"9">=c&&(c="#");switch(c){case "'":case '"':b.value=a.slice(1,-1);b.literal=!0;break;case "#":b.value=Number(a),b.literal=!0}b.literal||(b.model=Polymer.Path.root(a),
b.structured=Polymer.Path.isDeep(a),b.structured&&(b.wildcard=".*"==a.slice(-2),b.wildcard&&(b.name=a.slice(0,-2))));return b},_marshalInstanceEffects:function(){Polymer.Bind.prepareInstance(this);this._bindListeners&&Polymer.Bind.setupBindListeners(this)},_applyEffectValue:function(a,b){var c=this._nodes[a.index],d=a.name;b=this._computeFinalAnnotationValue(c,d,b,a);"attribute"==a.kind?this.serializeValueToAttribute(b,d,c):(a=c._propertyInfo&&c._propertyInfo[d])&&a.readOnly||this.__setProperty(d,
b,Polymer.Settings.suppressBindingNotifications,c)},_computeFinalAnnotationValue:function(a,b,c,d){d.negate&&(c=!c);if(d.isCompound){var e=a.__compoundStorage__[b];e[d.compoundIndex]=c;c=e.join("")}"attribute"!==d.kind&&("className"===b&&(c=this._scopeElementClass(a,c)),"textContent"===b||"input"==a.localName&&"value"==b)&&(c=void 0==c?"":c);return c},_executeStaticEffects:function(){this._propertyEffects&&this._propertyEffects.__static__&&this._effectEffects("__static__",null,this._propertyEffects.__static__)}});
(function(){var a=Polymer.Settings.usePolyfillProto,b=!!Object.getOwnPropertyDescriptor(document.documentElement,"properties");Polymer.Base._addFeature({_setupConfigure:function(c){this._config={};this._handlers=[];this._aboveConfig=null;if(c)for(var d in c)void 0!==c[d]&&(this._config[d]=c[d])},_marshalAttributes:function(){this._takeAttributesToModel(this._config)},_attributeChangedImpl:function(c){this._setAttributeToProperty(this._clientsReadied?this:this._config,c)},_configValue:function(c,d){var e=
this._propertyInfo[c];e&&e.readOnly||(this._config[c]=d)},_beforeClientsReady:function(){this._configure()},_configure:function(){this._configureAnnotationReferences();this._configureInstanceProperties();this._aboveConfig=this.mixin({},this._config);for(var c={},d=0;d<this.behaviors.length;d++)this._configureProperties(this.behaviors[d].properties,c);this._configureProperties(b?this.__proto__.properties:this.properties,c);this.mixin(c,this._aboveConfig);this._config=c;this._clients&&this._clients.length&&
this._distributeConfig(this._config)},_configureInstanceProperties:function(){for(var c in this._propertyEffects)!a&&this.hasOwnProperty(c)&&(this._configValue(c,this[c]),delete this[c])},_configureProperties:function(c,d){for(var e in c){var g=c[e];void 0!==g.value&&(g=g.value,"function"==typeof g&&(g=g.call(this,this._config)),d[e]=g)}},_distributeConfig:function(c){var d=this._propertyEffects;if(d)for(var e in c){var g=d[e];if(g)for(var h=0,k=g.length,l;h<k&&(l=g[h]);h++)if("annotation"===l.kind){var m=
this._nodes[l.effect.index],n=l.effect.propertyName,q="attribute"==l.effect.kind,p=m._propertyEffects&&m._propertyEffects[n];!m._configValue||!p&&q||(p=e===l.effect.value?c[e]:this._get(l.effect.value,c),p=this._computeFinalAnnotationValue(m,n,p,l.effect),q&&(p=m.deserialize(this.serialize(p),m._propertyInfo[n].type)),m._configValue(n,p))}}},_afterClientsReady:function(){this.importPath=this._importPath;this.rootPath=Polymer.rootPath;this._executeStaticEffects();this._applyConfig(this._config,this._aboveConfig);
this._flushHandlers()},_applyConfig:function(c,d){for(var e in c)void 0===this[e]&&this.__setProperty(e,c[e],e in d)},_notifyListener:function(c,d){if(!Polymer.Bind._isEventBogus(d,d.target)){if(d.detail){var e=d.detail.value;var g=d.detail.path}if(this._clientsReadied)return c.call(this,d.target,e,g);this._queueHandler([c,d.target,e,g])}},_queueHandler:function(c){this._handlers.push(c)},_flushHandlers:function(){for(var c=this._handlers,d=0,e=c.length,g;d<e&&(g=c[d]);d++)g[0].call(this,g[1],g[2],
g[3]);this._handlers=[]}})})();
(function(){var a=Polymer.Path;Polymer.Base._addFeature({notifyPath:function(b,c,d){var e={},g=this._get(b,this,e);1===arguments.length&&(c=g);e.path&&this._notifyPath(e.path,c,d)},_notifyPath:function(b,c,d){var e=this._propertySetter(b,c);if(e!==c&&(e===e||c===c))return this._pathEffector(b,c),d||this._notifyPathUp(b,c),!0},_getPathParts:function(b){if(Array.isArray(b)){for(var c=[],d=0;d<b.length;d++)for(var e=b[d].toString().split("."),g=0;g<e.length;g++)c.push(e[g]);return c}return b.toString().split(".")},
set:function(b,c,d){var e=d||this,g=this._getPathParts(b),h=g[g.length-1];if(1<g.length){for(b=0;b<g.length-1;b++){var k=g[b];l&&"#"==k[0]?e=Polymer.Collection.get(l).getItem(k):(e=e[k],l&&parseInt(k,10)==k&&(g[b]=Polymer.Collection.get(l).getKey(e)));if(!e)return;var l=Array.isArray(e)?e:null}if(l)if(k=Polymer.Collection.get(l),"#"==h[0]){var m=h;var n=k.getItem(m);h=l.indexOf(n);k.setItem(m,c)}else parseInt(h,10)==h&&(n=e[h],m=k.getKey(n),g[b]=m,k.setItem(m,c));e[h]=c;d||this._notifyPath(g.join("."),
c)}else e[b]=c},get:function(b,c){return this._get(b,c)},_get:function(b,c,d){c=c||this;b=this._getPathParts(b);for(var e,g=0;g<b.length;g++){if(!c)return;var h=b[g];e&&"#"==h[0]?c=Polymer.Collection.get(e).getItem(h):(c=c[h],d&&e&&parseInt(h,10)==h&&(b[g]=Polymer.Collection.get(e).getKey(c)));e=Array.isArray(c)?c:null}d&&(d.path=b.join("."));return c},_pathEffector:function(b,c){var d=a.root(b);if(d=this._propertyEffects&&this._propertyEffects[d])for(var e=0,g;e<d.length&&(g=d[e]);e++){var h=g.pathFn;
h&&h.call(this,b,c,g.effect)}this._boundPaths&&this._notifyBoundPaths(b,c)},_annotationPathEffect:function(b,c,d){if(a.matches(d.value,!1,b))Polymer.Bind._annotationEffect.call(this,b,c,d);else if(!d.negate&&a.isDescendant(d.value,b)){var e=this._nodes[d.index];e&&e._notifyPath&&(b=a.translate(d.value,d.name,b),e._notifyPath(b,c,!0))}},_complexObserverPathEffect:function(b,c,d){a.matches(d.trigger.name,d.trigger.wildcard,b)&&Polymer.Bind._complexObserverEffect.call(this,b,c,d)},_computePathEffect:function(b,
c,d){a.matches(d.trigger.name,d.trigger.wildcard,b)&&Polymer.Bind._computeEffect.call(this,b,c,d)},_annotatedComputationPathEffect:function(b,c,d){a.matches(d.trigger.name,d.trigger.wildcard,b)&&Polymer.Bind._annotatedComputationEffect.call(this,b,c,d)},linkPaths:function(b,c){this._boundPaths=this._boundPaths||{};c?this._boundPaths[b]=c:this.unlinkPaths(b)},unlinkPaths:function(b){this._boundPaths&&delete this._boundPaths[b]},_notifyBoundPaths:function(b,c){for(var d in this._boundPaths){var e=this._boundPaths[d];
a.isDescendant(d,b)?this._notifyPath(a.translate(d,e,b),c):a.isDescendant(e,b)&&this._notifyPath(a.translate(e,d,b),c)}},_notifyPathUp:function(b,c){var d=a.root(b);d=Polymer.CaseMap.camelToDashCase(d)+this._EVENT_CHANGED;this.fire(d,{path:b,value:c},{bubbles:!1,_useCache:Polymer.Settings.eventDataCache||!Polymer.Settings.isIE})},_EVENT_CHANGED:"-changed",notifySplices:function(b,c){var d={};b=this._get(b,this,d);this._notifySplices(b,d.path,c)},_notifySplices:function(b,c,d){d={keySplices:Polymer.Collection.applySplices(b,
d),indexSplices:d};var e=c+".splices";this._notifyPath(e,d);this._notifyPath(c+".length",b.length);this.__data__[e]={keySplices:null,indexSplices:null}},_notifySplice:function(b,c,d,e,g){this._notifySplices(b,c,[{index:d,addedCount:e,removed:g,object:b,type:"splice"}])},push:function(b){var c={},d=this._get(b,this,c),e=Array.prototype.slice.call(arguments,1),g=d.length,h=d.push.apply(d,e);e.length&&this._notifySplice(d,c.path,g,e.length,[]);return h},pop:function(b){var c={},d=this._get(b,this,c),
e=!!d.length,g=d.pop.apply(d,Array.prototype.slice.call(arguments,1));e&&this._notifySplice(d,c.path,d.length,0,[g]);return g},splice:function(b,c){var d={},e=this._get(b,this,d);(c=0>c?e.length-Math.floor(-c):Math.floor(c))||(c=0);var g=Array.prototype.slice.call(arguments,1),h=e.splice.apply(e,g);((g=Math.max(g.length-2,0))||h.length)&&this._notifySplice(e,d.path,c,g,h);return h},shift:function(b){var c={},d=this._get(b,this,c),e=!!d.length,g=d.shift.apply(d,Array.prototype.slice.call(arguments,
1));e&&this._notifySplice(d,c.path,0,0,[g]);return g},unshift:function(b){var c={},d=this._get(b,this,c),e=Array.prototype.slice.call(arguments,1),g=d.unshift.apply(d,e);e.length&&this._notifySplice(d,c.path,0,e.length,[]);return g},prepareModelNotifyPath:function(b){this.mixin(b,{fire:Polymer.Base.fire,_getEvent:Polymer.Base._getEvent,__eventCache:Polymer.Base.__eventCache,notifyPath:Polymer.Base.notifyPath,_get:Polymer.Base._get,_EVENT_CHANGED:Polymer.Base._EVENT_CHANGED,_notifyPath:Polymer.Base._notifyPath,
_notifyPathUp:Polymer.Base._notifyPathUp,_pathEffector:Polymer.Base._pathEffector,_annotationPathEffect:Polymer.Base._annotationPathEffect,_complexObserverPathEffect:Polymer.Base._complexObserverPathEffect,_annotatedComputationPathEffect:Polymer.Base._annotatedComputationPathEffect,_computePathEffect:Polymer.Base._computePathEffect,_notifyBoundPaths:Polymer.Base._notifyBoundPaths,_getPathParts:Polymer.Base._getPathParts})}})})();
Polymer.Base._addFeature({resolveUrl:function(a){return Polymer.ResolveUrl.resolveUrl(a,this._importPath)}});
Polymer.CssParse={parse:function(a){a=this._clean(a);return this._parseCss(this._lex(a),a)},_clean:function(a){return a.replace(this._rx.comments,"").replace(this._rx.port,"")},_lex:function(a){for(var b={start:0,end:a.length},c=b,d=0,e=a.length;d<e;d++)switch(a[d]){case this.OPEN_BRACE:c.rules||(c.rules=[]);var g=c;c={start:d+1,parent:g,previous:g.rules[g.rules.length-1]};g.rules.push(c);break;case this.CLOSE_BRACE:c.end=d+1,c=c.parent||b}return b},_parseCss:function(a,b){var c=b.substring(a.start,
a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=this._expandUnicodeEscapes(c),c=c.replace(this._rx.multipleSpaces," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf(this.AT_START),a.atRule?0===c.indexOf(this.MEDIA_START)?a.type=this.types.MEDIA_RULE:c.match(this._rx.keyframesRule)&&(a.type=this.types.KEYFRAMES_RULE,a.keyframesName=a.selector.split(this._rx.multipleSpaces).pop()):
a.type=0===c.indexOf(this.VAR_START)?this.types.MIXIN_RULE:this.types.STYLE_RULE);if(c=a.rules)for(var d=0,e=c.length,g;d<e&&(g=c[d]);d++)this._parseCss(g,b);return a},_expandUnicodeEscapes:function(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})},stringify:function(a,b,c){c=c||"";var d="";if(a.cssText||a.rules){var e=a.rules;if(e&&!this._hasMixinRules(e))for(var g=0,h=e.length,k;g<h&&(k=e[g]);g++)d=this.stringify(k,b,d);else d=b?a.cssText:
this.removeCustomProps(a.cssText),(d=d.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" "+this.OPEN_BRACE+"\n"),c+=d,a.selector&&(c+=this.CLOSE_BRACE+"\n\n"));return c},_hasMixinRules:function(a){return 0===a[0].selector.indexOf(this.VAR_START)},removeCustomProps:function(a){a=this.removeCustomPropAssignment(a);return this.removeCustomPropApply(a)},removeCustomPropAssignment:function(a){return a.replace(this._rx.customProp,"").replace(this._rx.mixinProp,"")},removeCustomPropApply:function(a){return a.replace(this._rx.mixinApply,
"").replace(this._rx.varApply,"")},types:{STYLE_RULE:1,KEYFRAMES_RULE:7,MEDIA_RULE:4,MIXIN_RULE:1E3},OPEN_BRACE:"{",CLOSE_BRACE:"}",_rx:{comments:/\/\*[^*]*\*+([^\/*][^*]*\*+)*\//gim,port:/@import[^;]*;/gim,customProp:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,mixinProp:/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,mixinApply:/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,varApply:/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,keyframesRule:/^@[^\s]*keyframes/,multipleSpaces:/\s+/g},
VAR_START:"--",MEDIA_START:"@media",AT_START:"@"};
Polymer.StyleUtil=function(){var a=Polymer.Settings;return{unscopedStyleImports:new WeakMap,SHADY_UNSCOPED_ATTR:"shady-unscoped",NATIVE_VARIABLES:Polymer.Settings.useNativeCSSProperties,MODULE_STYLES_SELECTOR:"style, link[rel\x3dimport][type~\x3dcss], template",INCLUDE_ATTR:"include",toCssText:function(b,c){"string"===typeof b&&(b=this.parser.parse(b));c&&this.forEachRule(b,c);return this.parser.stringify(b,this.NATIVE_VARIABLES)},forRulesInStyles:function(b,c,d){if(b)for(var e=0,g=b.length,h;e<g&&
(h=b[e]);e++)this.forEachRuleInStyle(h,c,d)},forActiveRulesInStyles:function(b,c,d){if(b)for(var e=0,g=b.length,h;e<g&&(h=b[e]);e++)this.forEachRuleInStyle(h,c,d,!0)},rulesForStyle:function(b){!b.__cssRules&&b.textContent&&(b.__cssRules=this.parser.parse(b.textContent));return b.__cssRules},isKeyframesSelector:function(b){return b.parent&&b.parent.type===this.ruleTypes.KEYFRAMES_RULE},forEachRuleInStyle:function(b,c,d,e){var g=this.rulesForStyle(b),h,k;c&&(h=function(l){c(l,b)});d&&(k=function(l){d(l,
b)});this.forEachRule(g,h,k,e)},forEachRule:function(b,c,d,e){if(b){var g=!1;if(e&&b.type===this.ruleTypes.MEDIA_RULE){var h=b.selector.match(this.rx.MEDIA_MATCH);h&&(window.matchMedia(h[1]).matches||(g=!0))}b.type===this.ruleTypes.STYLE_RULE?c(b):d&&b.type===this.ruleTypes.KEYFRAMES_RULE?d(b):b.type===this.ruleTypes.MIXIN_RULE&&(g=!0);if((b=b.rules)&&!g){g=0;h=b.length;for(var k;g<h&&(k=b[g]);g++)this.forEachRule(k,c,d,e)}}},applyCss:function(b,c,d,e){b=this.createScopeStyle(b,c);return this.applyStyle(b,
d,e)},applyStyle:function(b,c,d){c=c||document.head;d=d&&d.nextSibling||c.firstChild;this.__lastHeadApplyNode=b;return c.insertBefore(b,d)},createScopeStyle:function(b,c){var d=document.createElement("style");c&&d.setAttribute("scope",c);d.textContent=b;return d},__lastHeadApplyNode:null,applyStylePlaceHolder:function(b){b=document.createComment(" Shady DOM styles for "+b+" ");var c=document.head;c.insertBefore(b,(this.__lastHeadApplyNode?this.__lastHeadApplyNode.nextSibling:null)||c.firstChild);
return this.__lastHeadApplyNode=b},cssFromModules:function(b,c){b=b.trim().split(/\s+/);for(var d="",e=0;e<b.length;e++)d+=this.cssFromModule(b[e],c);return d},cssFromModule:function(b,c){var d=Polymer.DomModule.import(b);d&&!d._cssText&&(d._cssText=this.cssFromElement(d));!d&&c&&console.warn("Could not find style data in module named",b);return d&&d._cssText||""},cssFromElement:function(b){for(var c="",d=Polymer.TreeApi.arrayCopy((b.content||b).querySelectorAll(this.MODULE_STYLES_SELECTOR)),e=0,
g;e<d.length;e++)if(g=d[e],"template"===g.localName)g.hasAttribute("preserve-content")||(c+=this.cssFromElement(g));else if("style"===g.localName){var h=g.getAttribute(this.INCLUDE_ATTR);h&&(c+=this.cssFromModules(h,!0));g=g.__appliedElement||g;g.parentNode.removeChild(g);h=this.resolveCss(g.textContent,b.ownerDocument);!a.useNativeShadow&&g.hasAttribute(this.SHADY_UNSCOPED_ATTR)?(g.textContent=h,document.head.insertBefore(g,document.head.firstChild)):c+=h}else g.import&&g.import.body&&(h=this.resolveCss(g.import.body.textContent,
g.import),!a.useNativeShadow&&g.hasAttribute(this.SHADY_UNSCOPED_ATTR)?this.unscopedStyleImports.has(g.import)||(this.unscopedStyleImports.set(g.import,!0),g=document.createElement("style"),g.setAttribute(this.SHADY_UNSCOPED_ATTR,""),g.textContent=h,document.head.insertBefore(g,document.head.firstChild)):c+=h);return c},styleIncludesToTemplate:function(b){b=b.content.querySelectorAll("style[include]");for(var c=0,d;c<b.length;c++)d=b[c],d.parentNode.insertBefore(this._includesToFragment(d.getAttribute("include")),
d)},_includesToFragment:function(b){b=b.trim().split(" ");for(var c=document.createDocumentFragment(),d=0;d<b.length;d++){var e=Polymer.DomModule.import(b[d],"template");e&&this._addStylesToFragment(c,e.content)}return c},_addStylesToFragment:function(b,c){c=c.querySelectorAll("style");for(var d=0,e;d<c.length;d++){e=c[d];var g=e.getAttribute("include");g&&b.appendChild(this._includesToFragment(g));e.textContent&&b.appendChild(e.cloneNode(!0))}},isTargetedBuild:function(b){return a.useNativeShadow?
"shadow"===b:"shady"===b},cssBuildTypeForModule:function(b){if(b=Polymer.DomModule.import(b))return this.getCssBuildType(b)},getCssBuildType:function(b){return b.getAttribute("css-build")},_findMatchingParen:function(b,c){for(var d=0,e=b.length;c<e;c++)switch(b[c]){case "(":d++;break;case ")":if(0===--d)return c}return-1},processVariableAndFallback:function(b,c){var d=b.indexOf("var(");if(-1===d)return c(b,"","","");var e=this._findMatchingParen(b,d+3),g=b.substring(d+4,e);d=b.substring(0,d);b=this.processVariableAndFallback(b.substring(e+
1),c);var h=g.indexOf(",");if(-1===h)return c(d,g.trim(),"",b);e=g.substring(0,h).trim();g=g.substring(h+1).trim();return c(d,e,g,b)},rx:{VAR_ASSIGN:/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:([^;{]*)|{([^}]*)})(?:(?=[;\s}])|$)/gi,MIXIN_MATCH:/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,VAR_CONSUMED:/(--[\w-]+)\s*([:,;)]|$)/gi,ANIMATION_MATCH:/(animation\s*:)|(animation-name\s*:)/,MEDIA_MATCH:/@media[^(]*(\([^)]*\))/,IS_VAR:/^--/,BRACKETED:/\{[^}]*\}/g,HOST_PREFIX:"(?:^|[^.#[:])",HOST_SUFFIX:"($|[.:[\\s\x3e+~])"},
resolveCss:Polymer.ResolveUrl.resolveCss,parser:Polymer.CssParse,ruleTypes:Polymer.CssParse.types}}();
Polymer.StyleTransformer=function(){var a=Polymer.StyleUtil,b=Polymer.Settings,c={dom:function(H,O,P,D){this._transformDom(H,O||"",P,D)},_transformDom:function(H,O,P,D){H.setAttribute&&this.element(H,O,P,D);H=Polymer.dom(H).childNodes;for(var R=0;R<H.length;R++)this._transformDom(H[R],O,P,D)},element:function(H,O,P,D){P?D?H.removeAttribute(d):H.setAttribute(d,O):O&&(H.classList?D?(H.classList.remove(d),H.classList.remove(O)):(H.classList.add(d),H.classList.add(O)):H.getAttribute&&(P=H.getAttribute(A),
D?P&&H.setAttribute(A,P.replace(d,"").replace(O,"")):H.setAttribute(A,(P?P+" ":"")+d+" "+O)))},elementStyles:function(H,O){var P=H._styles,D="",R=H.__cssBuild;R=b.useNativeShadow||"shady"===R;if(R){var U=this;var I=function(Y){Y.selector=U._slottedToContent(Y.selector);Y.selector=Y.selector.replace(m,":host \x3e *");Y.selector=U._dirShadowTransform(Y.selector);O&&O(Y)}}for(var J=0,S=P.length,X;J<S&&(X=P[J]);J++){var M=a.rulesForStyle(X);D+=R?a.toCssText(M,I):this.css(M,H.is,H.extends,O,H._scopeCssViaAttr)+
"\n\n"}return D.trim()},css:function(H,O,P,D,R){var U=this._calcHostScope(O,P);O=this._calcElementScope(O,R);var I=this;return a.toCssText(H,function(J){J.isScoped||(I.rule(J,O,U),J.isScoped=!0);D&&D(J,O,U)})},_calcElementScope:function(H,O){return H?O?u+H+w:v+H:""},_calcHostScope:function(H,O){return O?"[is\x3d"+H+"]":H},rule:function(H,O,P){this._transformRule(H,this._transformComplexSelector,O,P)},_transformRule:function(H,O,P,D){H.selector=H.transformedSelector=this._transformRuleCss(H,O,P,D)},
_splitSelectorList:function(H){for(var O=[],P="",D=0;0<=D&&D<H.length;D++)if("("===H[D]){var R=a._findMatchingParen(H,D);P+=H.slice(D,R+1);D=R}else H[D]===g?(O.push(P),P=""):P+=H[D];P&&O.push(P);0===O.length&&O.push(H);return O},_transformRuleCss:function(H,O,P,D){var R=this._splitSelectorList(H.selector);if(!a.isKeyframesSelector(H)){H=0;for(var U=R.length,I;H<U&&(I=R[H]);H++)R[H]=O.call(this,I,P,D)}return R.join(g)},_ensureScopedDir:function(H){var O=H.match(L);O&&""===O[1]&&O[0].length===H.length&&
(H="*"+H);return H},_additionalDirSelectors:function(H,O,P){return H&&O?g+(P||"")+" "+H+" "+O:""},_transformComplexSelector:function(H,O,P){var D=!1,R=!1,U=!1,I=this;H=H.trim();H=this._slottedToContent(H);H=H.replace(m,":host \x3e *");H=H.replace(y,l+" $1");H=this._ensureScopedDir(H);H=H.replace(h,function(J,S,X){D?X=X.replace(r," "):(J=I._transformCompoundSelector(X,S,O,P),D=D||J.stop,R=R||J.hostContext,U=U||J.dir,S=J.combinator,X=J.value);return S+X});R&&(H=H.replace(p,function(J,S,X,M){J=S+X+" "+
P+M+g+" "+S+P+X+M;U&&(J+=I._additionalDirSelectors(X,M,P));return J}));return H},_transformDir:function(H){H=H.replace(Q,W);return H=H.replace(L,N)},_transformCompoundSelector:function(H,O,P,D){var R=H.search(r),U=!1,I=!1;H.match(L)&&(H=this._transformDir(H),I=!0);0<=H.indexOf(q)?U=!0:0<=H.indexOf(l)?H=this._transformHostSelector(H,D):0!==R&&(H=P?this._transformSimpleSelector(H,P):H);0<=H.indexOf(t)&&(O="");if(0<=R){H=H.replace(r," ");var J=!0}return{value:H,combinator:O,stop:J,hostContext:U,dir:I}},
_transformSimpleSelector:function(H,O){H=H.split(x);H[0]+=O;return H.join(x)},_transformHostSelector:function(H,O){var P=H.match(n);return(P=P&&P[2].trim()||"")?P[0].match(k)?H.replace(n,function(D,R,U){return O+U}):P.split(k)[0]===O?P:B:H.replace(l,O)},documentRule:function(H){H.selector=H.parsedSelector;this.normalizeRootSelector(H);b.useNativeShadow||this._transformRule(H,this._transformDocumentSelector)},normalizeRootSelector:function(H){H.selector=H.selector.replace(m,"html");var O=this._splitSelectorList(H.selector);
O=O.filter(function(P){return!P.match(K)});H.selector=O.join(g)},_transformDocumentSelector:function(H){return this._transformComplexSelector(H,e)},_slottedToContent:function(H){return H.replace(F,t+"\x3e $1")},_dirShadowTransform:function(H){return H.match(/:dir\(/)?this._splitSelectorList(H).map(function(O){O=this._ensureScopedDir(O);O=this._transformDir(O);var P=p.exec(O);P&&(O+=this._additionalDirSelectors(P[2],P[3],""));return O},this).join(g):H},SCOPE_NAME:"style-scope"},d=c.SCOPE_NAME,e=":not(["+
d+"]):not(."+d+")",g=",",h=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=\[])+)/g,k=/[[.:#*]/,l=":host",m=":root",n=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,q=":host-context",p=/(.*)(?::host-context)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))(.*)/,t="::content",r=/::content|::shadow|\/deep\//,v=".",u="["+d+"~\x3d",w="]",x=":",A="class",y=new RegExp("^("+t+")"),B="should_not_match",F=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/g,K=/:host(?:\s*>\s*\*)?/,L=/(.*):dir\((ltr|rtl)\)/,N=':host-context([dir\x3d"$2"]) $1',
Q=/:host\(:dir\((rtl|ltr)\)\)/g,W=':host-context([dir\x3d"$1"])';return c}();
Polymer.StyleExtends=function(){var a=Polymer.StyleUtil;return{hasExtends:function(b){return!!b.match(this.rx.EXTEND)},transform:function(b){b=a.rulesForStyle(b);var c=this;a.forEachRule(b,function(d){c._mapRuleOntoParent(d);if(d.parent)for(var e;e=c.rx.EXTEND.exec(d.cssText);)(e=c._findExtendor(e[1],d))&&c._extendRule(d,e);d.cssText=d.cssText.replace(c.rx.EXTEND,"")});return a.toCssText(b,function(d){d.selector.match(c.rx.STRIP)&&(d.cssText="")},!0)},_mapRuleOntoParent:function(b){if(b.parent){for(var c=
b.parent.map||(b.parent.map={}),d=b.selector.split(","),e=0,g;e<d.length;e++)g=d[e],c[g.trim()]=b;return c}},_findExtendor:function(b,c){return c.parent&&c.parent.map&&c.parent.map[b]||this._findExtendor(b,c.parent)},_extendRule:function(b,c){b.parent!==c.parent&&this._cloneAndAddRuleToParent(c,b.parent);b.extends=b.extends||[];b.extends.push(c);c.selector=c.selector.replace(this.rx.STRIP,"");c.selector=(c.selector&&c.selector+",\n")+b.selector;c.extends&&c.extends.forEach(function(d){this._extendRule(b,
d)},this)},_cloneAndAddRuleToParent:function(b,c){b=Object.create(b);b.parent=c;b.extends&&(b.extends=b.extends.slice());c.rules.push(b)},rx:{EXTEND:/@extends\(([^)]*)\)\s*?;/gim,STRIP:/%[^,]*$/}}}();
Polymer.ApplyShim=function(){function a(v,u){v=v.trim();t[v]={properties:u,dependants:{}}}function b(v){v=v.trim();return t[v]}function c(v){v=v.split(";");for(var u,w,x={},A=0,y;A<v.length;A++)if(u=v[A])if(y=u.split(":"),1<y.length){w=u=y[0].trim();y=y.slice(1).join(":");var B=p.exec(y);B&&(y=B[1]?r._getInitialValueForProperty(w):"apply-shim-inherit");w=y;x[u]=w}return x}function d(v){var u=r.__currentElementProto;u=u&&u.is;for(var w in v.dependants)w!==u&&(v.dependants[w].__applyShimInvalid=!0)}
function e(v,u,w,x){w&&k.processVariableAndFallback(w,function(H,O){O&&b(O)&&(x="@apply "+O+";")});if(!x)return v;var A=h(x),y=v.slice(0,v.indexOf("--")),B=A=c(A),F=b(u),K=F&&F.properties;K?(B=Object.create(K),B=Polymer.Base.mixin(B,A)):a(u,B);var L=[],N,Q=!1;for(N in B){var W=A[N];void 0===W&&(W="initial");!K||N in K||(Q=!0);L.push(u+"_-_"+N+": "+W)}Q&&d(F);F&&(F.properties=B);w&&(y=v+";"+y);return y+L.join("; ")+";"}function g(v,u,w){return"var("+u+",var("+w+"))"}function h(v){for(var u;u=l.exec(v);){var w=
u[0],x=u[1];u=u.index;var A=v.slice(0,u+w.indexOf("@apply"));v=v.slice(u+w.length);var y=c(A),B;w=void 0;x=x.replace(q,"");var F=[];var K=b(x);K||(a(x,{}),K=b(x));if(K)for(w in(B=r.__currentElementProto)&&(K.dependants[B.is]=B),K.properties)K=y&&y[w],B=[w,": var(",x,"_-_",w],K&&B.push(",",K),B.push(")"),F.push(B.join(""));w=F.join("; ");v=[A,w,v].join("");l.lastIndex=u+w.length}return v}var k=Polymer.StyleUtil,l=k.rx.MIXIN_MATCH,m=k.rx.VAR_ASSIGN,n=/var\(\s*(--[^,]*),\s*(--[^)]*)\)/g,q=/;\s*/m,p=
/^\s*(initial)|(inherit)\s*$/,t={},r={_measureElement:null,_map:t,_separator:"_-_",transform:function(v,u){this.__currentElementProto=u;k.forRulesInStyles(v,this._boundFindDefinitions);k.forRulesInStyles(v,this._boundFindApplications);u&&(u.__applyShimInvalid=!1);this.__currentElementProto=null},_findDefinitions:function(v){var u=v.parsedCssText;u=u.replace(n,g);u=u.replace(m,e);v.cssText=u;":root"===v.selector&&(v.selector=":host \x3e *")},_findApplications:function(v){v.cssText=h(v.cssText)},transformRule:function(v){this._findDefinitions(v);
this._findApplications(v)},_getInitialValueForProperty:function(v){this._measureElement||(this._measureElement=document.createElement("meta"),this._measureElement.style.all="initial",document.head.appendChild(this._measureElement));return window.getComputedStyle(this._measureElement).getPropertyValue(v)}};r._boundTransformRule=r.transformRule.bind(r);r._boundFindDefinitions=r._findDefinitions.bind(r);r._boundFindApplications=r._findApplications.bind(r);return r}();
(function(){var a=Polymer.Base._prepElement,b=Polymer.Settings.useNativeShadow,c=Polymer.StyleUtil,d=Polymer.StyleTransformer,e=Polymer.StyleExtends,g=Polymer.ApplyShim,h=Polymer.Settings;Polymer.Base._addFeature({_prepElement:function(k){this._encapsulateStyle&&"shady"!==this.__cssBuild&&d.element(k,this.is,this._scopeCssViaAttr);a.call(this,k)},_prepStyles:function(){void 0===this._encapsulateStyle&&(this._encapsulateStyle=!b);b||(this._scopeStyle=c.applyStylePlaceHolder(this.is));this.__cssBuild=
c.cssBuildTypeForModule(this.is)},_prepShimStyles:function(){if(this._template){var k=c.isTargetedBuild(this.__cssBuild);h.useNativeCSSProperties&&"shadow"===this.__cssBuild&&k?h.preserveStyleIncludes&&c.styleIncludesToTemplate(this._template):(this._styles=this._styles||this._collectStyles(),h.useNativeCSSProperties&&!this.__cssBuild&&g.transform(this._styles,this),k=h.useNativeCSSProperties&&k?this._styles.length&&this._styles[0].textContent.trim():d.elementStyles(this),this._prepStyleProperties(),
!this._needsStyleProperties()&&k&&c.applyCss(k,this.is,b?this._template.content:null,this._scopeStyle))}else this._styles=[]},_collectStyles:function(){var k=[],l="",m=this.styleModules;if(m)for(var n=0,q=m.length,p;n<q&&(p=m[n]);n++)l+=c.cssFromModule(p);l+=c.cssFromModule(this.is);m=this._template&&this._template.parentNode;!this._template||m&&m.id.toLowerCase()===this.is||(l+=c.cssFromElement(this._template));l&&(m=document.createElement("style"),m.textContent=l,e.hasExtends(m.textContent)&&e.transform(m),
k.push(m));return k},_elementAdd:function(k){this._encapsulateStyle&&(k.__styleScoped?k.__styleScoped=!1:d.dom(k,this.is,this._scopeCssViaAttr))},_elementRemove:function(k){this._encapsulateStyle&&d.dom(k,this.is,this._scopeCssViaAttr,!0)},scopeSubtree:function(k,l){if(!b){var m=this,n=function(q){if(q.nodeType===Node.ELEMENT_NODE){var p=q.getAttribute("class");q.setAttribute("class",m._scopeElementClass(q,p));q=q.querySelectorAll("*");for(var t=0,r;t<q.length&&(r=q[t]);t++)p=r.getAttribute("class"),
r.setAttribute("class",m._scopeElementClass(r,p))}};n(k);if(l)return l=new MutationObserver(function(q){for(var p=0,t;p<q.length&&(t=q[p]);p++)if(t.addedNodes)for(var r=0;r<t.addedNodes.length;r++)n(t.addedNodes[r])}),l.observe(k,{childList:!0,subtree:!0}),l}}})})();
Polymer.StyleProperties=function(){var a=Polymer.DomApi.matchesSelector,b=Polymer.StyleUtil,c=Polymer.StyleTransformer,d=navigator.userAgent.match("Trident"),e=Polymer.Settings;return{decorateStyles:function(g,h){var k=this,l={},m=[],n=0,q=c._calcHostScope(h.is,h.extends);b.forRulesInStyles(g,function(t,r){k.decorateRule(t);t.index=n++;k.whenHostOrRootRule(h,t,r,function(v){t.parent.type===b.ruleTypes.MEDIA_RULE&&(h.__notStyleScopeCacheable=!0);v.isHost&&(v=v.selector.split(" ").some(function(u){return 0===
u.indexOf(q)&&u.length!==q.length}),h.__notStyleScopeCacheable=h.__notStyleScopeCacheable||v)});k.collectPropertiesInCssText(t.propertyInfo.cssText,l)},function(t){m.push(t)});g._keyframes=m;g=[];for(var p in l)g.push(p);return g},decorateRule:function(g){if(g.propertyInfo)return g.propertyInfo;var h={},k={};this.collectProperties(g,k)&&(h.properties=k,g.rules=null);h.cssText=this.collectCssText(g);return g.propertyInfo=h},collectProperties:function(g,h){var k=g.propertyInfo;if(k){if(k.properties)return Polymer.Base.mixin(h,
k.properties),!0}else{k=this.rx.VAR_ASSIGN;for(var l=g.parsedCssText,m;g=k.exec(l);)m=(g[2]||g[3]).trim(),"inherit"!==m&&(h[g[1].trim()]=m),m=!0;return m}},collectCssText:function(g){return this.collectConsumingCssText(g.parsedCssText)},collectConsumingCssText:function(g){return g.replace(this.rx.BRACKETED,"").replace(this.rx.VAR_ASSIGN,"")},collectPropertiesInCssText:function(g,h){for(var k;k=this.rx.VAR_CONSUMED.exec(g);){var l=k[1];":"!==k[2]&&(h[l]=!0)}},reify:function(g){for(var h=Object.getOwnPropertyNames(g),
k=0,l;k<h.length;k++)l=h[k],g[l]=this.valueForProperty(g[l],g)},valueForProperty:function(g,h){if(g)if(0<=g.indexOf(";"))g=this.valueForProperties(g,h);else{var k=this;g=b.processVariableAndFallback(g,function(l,m,n,q){(m=k.valueForProperty(h[m],h))&&"initial"!==m?"apply-shim-inherit"===m&&(m="inherit"):m=k.valueForProperty(h[n]||n,h)||n;return l+(m||"")+q})}return g&&g.trim()||""},valueForProperties:function(g,h){g=g.split(";");for(var k=0,l,m;k<g.length;k++)if(l=g[k]){this.rx.MIXIN_MATCH.lastIndex=
0;if(m=this.rx.MIXIN_MATCH.exec(l))l=this.valueForProperty(h[m[1]],h);else if(m=l.indexOf(":"),-1!==m){var n=l.substring(m);n=n.trim();n=this.valueForProperty(n,h)||n;l=l.substring(0,m)+n}g[k]=l&&l.lastIndexOf(";")===l.length-1?l.slice(0,-1):l||""}return g.join(";")},applyProperties:function(g,h){var k="";g.propertyInfo||this.decorateRule(g);g.propertyInfo.cssText&&(k=this.valueForProperties(g.propertyInfo.cssText,h));g.cssText=k},applyKeyframeTransforms:function(g,h){var k=g.cssText,l=g.cssText;
null==g.hasAnimations&&(g.hasAnimations=this.rx.ANIMATION_MATCH.test(k));if(g.hasAnimations)if(null==g.keyframeNamesToTransform){g.keyframeNamesToTransform=[];for(var m in h)l=h[m],l=l(k),k!==l&&(k=l,g.keyframeNamesToTransform.push(m))}else{for(m=0;m<g.keyframeNamesToTransform.length;++m)l=h[g.keyframeNamesToTransform[m]],k=l(k);l=k}g.cssText=l},propertyDataFromStyles:function(g,h){var k={},l=this,m=[];b.forActiveRulesInStyles(g,function(n){n.propertyInfo||l.decorateRule(n);var q=n.transformedSelector||
n.parsedSelector;h&&n.propertyInfo.properties&&q&&a.call(h,q)&&(l.collectProperties(n,k),n=n.index,q=parseInt(n/32),m[q]=(m[q]||0)|1<<n%32)});return{properties:k,key:m}},_rootSelector:/:root|:host\s*>\s*\*/,_checkRoot:function(g,h){return!!h.match(this._rootSelector)||"html"===g&&-1<h.indexOf("html")},whenHostOrRootRule:function(g,h,k,l){h.propertyInfo||self.decorateRule(h);if(h.propertyInfo.properties){var m=g.is?c._calcHostScope(g.is,g.extends):"html",n=h.parsedSelector,q=this._checkRoot(m,n),p=
!q&&0===n.indexOf(":host");"shady"===(g.__cssBuild||k.__cssBuild)&&(q=n===m+" \x3e *."+m||-1<n.indexOf("html"),p=!q&&0===n.indexOf(m));if(q||p)k=m,p&&(e.useNativeShadow&&!h.transformedSelector&&(h.transformedSelector=c._transformRuleCss(h,c._transformComplexSelector,g.is,m)),k=h.transformedSelector||h.parsedSelector),q&&"html"===m&&(k=h.transformedSelector||h.parsedSelector),l({selector:k,isHost:p,isRoot:q})}},hostAndRootPropertiesForScope:function(g){var h={},k={},l=this;b.forActiveRulesInStyles(g._styles,
function(m,n){l.whenHostOrRootRule(g,m,n,function(q){a.call(g._element||g,q.selector)&&(q.isHost?l.collectProperties(m,h):l.collectProperties(m,k))})});return{rootProps:k,hostProps:h}},transformStyles:function(g,h,k){var l=this,m=c._calcHostScope(g.is,g.extends),n=new RegExp(this.rx.HOST_PREFIX+(g.extends?"\\"+m.slice(0,-1)+"\\]":m)+this.rx.HOST_SUFFIX),q=this._elementKeyframeTransforms(g,k);return c.elementStyles(g,function(p){l.applyProperties(p,h);e.useNativeShadow||Polymer.StyleUtil.isKeyframesSelector(p)||
!p.cssText||(l.applyKeyframeTransforms(p,q),l._scopeSelector(p,n,m,g._scopeCssViaAttr,k))})},_elementKeyframeTransforms:function(g,h){g=g._styles._keyframes;var k={};if(!e.useNativeShadow&&g)for(var l=0,m=g[l];l<g.length;m=g[++l])this._scopeKeyframes(m,h),k[m.keyframesName]=this._keyframesRuleTransformer(m);return k},_keyframesRuleTransformer:function(g){return function(h){return h.replace(g.keyframesNameRx,g.transformedKeyframesName)}},_scopeKeyframes:function(g,h){g.keyframesNameRx=new RegExp("\\b"+
g.keyframesName+"(?!\\B|-)","g");g.transformedKeyframesName=g.keyframesName+"-"+h;g.transformedSelector=g.transformedSelector||g.selector;g.selector=g.transformedSelector.replace(g.keyframesName,g.transformedKeyframesName)},_hasDirOrHostContext:function(g){return/:host-context|:dir/.test(g)},_scopeSelector:function(g,h,k,l,m){g.transformedSelector=g.transformedSelector||g.selector;m=c._calcElementScope(m,l);l=c._calcElementScope(k,l);for(var n=g.transformedSelector.split(","),q=this._hasDirOrHostContext(g.parsedSelector),
p=0,t=n.length,r;p<t&&(r=n[p]);p++)n[p]=r.match(h)?r.replace(k,m):q?r.replace(l,m+" "+l):m+" "+r;g.selector=n.join(",")},applyElementScopeSelector:function(g,h,k,l){var m=l?g.getAttribute(c.SCOPE_NAME):g.getAttribute("class")||"";h=k?m.replace(k,h):(m?m+" ":"")+this.XSCOPE_NAME+" "+h;m!==h&&(l?g.setAttribute(c.SCOPE_NAME,h):g.setAttribute("class",h))},applyElementStyle:function(g,h,k,l){h=l?l.textContent||"":this.transformStyles(g,h,k);var m=g._customStyle;m&&!e.useNativeShadow&&m!==l&&(m._useCount--,
0>=m._useCount&&m.parentNode&&m.parentNode.removeChild(m));e.useNativeShadow?g._customStyle?(g._customStyle.textContent=h,l=g._customStyle):h&&(l=b.applyCss(h,k,g.root,g._scopeStyle)):l?l.parentNode||(d&&-1<h.indexOf("@media")&&(l.textContent=h),b.applyStyle(l,null,g._scopeStyle)):h&&(l=b.applyCss(h,k,null,g._scopeStyle));l&&(l._useCount=l._useCount||0,g._customStyle!=l&&l._useCount++,g._customStyle=l);return l},mixinCustomStyle:function(g,h){var k,l;for(l in h)if((k=h[l])||0===k)g[l]=k},updateNativeStyleProperties:function(g,
h){var k=g.__customStyleProperties;if(k)for(var l=0;l<k.length;l++)g.style.removeProperty(k[l]);k=[];for(var m in h)null!==h[m]&&(g.style.setProperty(m,h[m]),k.push(m));g.__customStyleProperties=k},rx:b.rx,XSCOPE_NAME:"x-scope"}}();Polymer.StyleCache=function(){this.cache={}};
Polymer.StyleCache.prototype={MAX:100,store:function(a,b,c,d){b.keyValues=c;b.styles=d;a=this.cache[a]=this.cache[a]||[];a.push(b);a.length>this.MAX&&a.shift()},retrieve:function(a,b,c){if(a=this.cache[a])for(var d=a.length-1,e;0<=d;d--)if(e=a[d],c===e.styles&&this._objectsEqual(b,e.keyValues))return e},clear:function(){this.cache={}},_objectsEqual:function(a,b){var c;for(c in a){var d=a[c];var e=b[c];if("object"===typeof d&&d?!this._objectsStrictlyEqual(d,e):d!==e)return!1}return Array.isArray(a)?
a.length===b.length:!0},_objectsStrictlyEqual:function(a,b){return this._objectsEqual(a,b)&&this._objectsEqual(b,a)}};
Polymer.StyleDefaults=function(){var a=Polymer.StyleProperties,b=Polymer.Settings.useNativeCSSProperties;return{_styles:[],_properties:null,customStyle:{},_styleCache:new Polymer.StyleCache,_element:Polymer.DomApi.wrap(document.documentElement),addStyle:function(c){this._styles.push(c);this._properties=null},get _styleProperties(){this._properties||(a.decorateStyles(this._styles,this),this._styles._scopeStyleProperties=null,this._properties=a.hostAndRootPropertiesForScope(this).rootProps,a.mixinCustomStyle(this._properties,
this.customStyle),a.reify(this._properties));return this._properties},hasStyleProperties:function(){return!!this._properties},_needsStyleProperties:function(){},_computeStyleProperties:function(){return this._styleProperties},updateStyles:function(c){this._properties=null;c&&Polymer.Base.mixin(this.customStyle,c);this._styleCache.clear();c=0;for(var d;c<this._styles.length;c++)d=this._styles[c],d=d.__importElement||d,d._apply();b&&a.updateNativeStyleProperties(document.documentElement,this.customStyle)}}}();
(function(){var a=Polymer.Base.serializeValueToAttribute,b=Polymer.StyleProperties,c=Polymer.StyleTransformer,d=Polymer.StyleDefaults,e=Polymer.Settings.useNativeShadow,g=Polymer.Settings.useNativeCSSProperties;Polymer.Base._addFeature({_prepStyleProperties:function(){g||(this._ownStylePropertyNames=this._styles&&this._styles.length?b.decorateStyles(this._styles,this):null)},customStyle:null,getComputedStyleValue:function(m){g||this._styleProperties||this._computeStyleProperties();return!g&&this._styleProperties&&
this._styleProperties[m]||getComputedStyle(this).getPropertyValue(m)},_setupStyleProperties:function(){this.customStyle={};this._customStyle=this._ownStyleProperties=this._scopeSelector=this._styleProperties=this._styleCache=null},_needsStyleProperties:function(){return!(g||!this._ownStylePropertyNames||!this._ownStylePropertyNames.length)},_validateApplyShim:function(){if(this.__applyShimInvalid){Polymer.ApplyShim.transform(this._styles,this.__proto__);var m=c.elementStyles(this);if(e){var n=this._template.content.querySelector("style");
n&&(n.textContent=m)}else if(n=this._scopeStyle&&this._scopeStyle.nextSibling)n.textContent=m}},_beforeAttached:function(){this._scopeSelector&&!this.__stylePropertiesInvalid||!this._needsStyleProperties()||(this.__stylePropertiesInvalid=!1,this._updateStyleProperties())},_findStyleHost:function(){for(var m=this;m=Polymer.dom(m).getOwnerRoot();){if(Polymer.isInstance(m.host))return m.host;m=m.host}return d},_updateStyleProperties:function(){var m=this._findStyleHost();m._styleProperties||m._computeStyleProperties();
m._styleCache||(m._styleCache=new Polymer.StyleCache);var n=b.propertyDataFromStyles(m._styles,this),q=!this.__notStyleScopeCacheable;if(q){n.key.customStyle=this.customStyle;var p=m._styleCache.retrieve(this.is,n.key,this._styles)}var t=!!p;t?this._styleProperties=p._styleProperties:this._computeStyleProperties(n.properties);this._computeOwnStyleProperties();t||(p=h.retrieve(this.is,this._ownStyleProperties,this._styles));var r=!!p&&!t;p=this._applyStyleProperties(p);t||(p=p&&e?p.cloneNode(!0):p,
p={style:p,_scopeSelector:this._scopeSelector,_styleProperties:this._styleProperties},q&&(n.key.customStyle={},this.mixin(n.key.customStyle,this.customStyle),m._styleCache.store(this.is,p,n.key,this._styles)),r||h.store(this.is,Object.create(p),this._ownStyleProperties,this._styles))},_computeStyleProperties:function(m){var n=this._findStyleHost();n._styleProperties||n._computeStyleProperties();var q=Object.create(n._styleProperties),p=b.hostAndRootPropertiesForScope(this);this.mixin(q,p.hostProps);
m=m||b.propertyDataFromStyles(n._styles,this).properties;this.mixin(q,m);this.mixin(q,p.rootProps);b.mixinCustomStyle(q,this.customStyle);b.reify(q);this._styleProperties=q},_computeOwnStyleProperties:function(){for(var m={},n=0,q;n<this._ownStylePropertyNames.length;n++)q=this._ownStylePropertyNames[n],m[q]=this._styleProperties[q];this._ownStyleProperties=m},_scopeCount:0,_applyStyleProperties:function(m){var n=this._scopeSelector;this._scopeSelector=m?m._scopeSelector:this.is+"-"+this.__proto__._scopeCount++;
m=b.applyElementStyle(this,this._styleProperties,this._scopeSelector,m&&m.style);e||b.applyElementScopeSelector(this,this._scopeSelector,n,this._scopeCssViaAttr);return m},serializeValueToAttribute:function(m,n,q){q=q||this;if("class"===n&&!e){var p=q===this?this.domHost||this.dataHost:this;p&&(m=p._scopeElementClass(q,m))}q=this.shadyRoot&&this.shadyRoot._hasDistributed?Polymer.dom(q):q;a.call(this,m,n,q)},_scopeElementClass:function(m,n){e||this._scopeCssViaAttr||(n=(n?n+" ":"")+k+" "+this.is+(m._scopeSelector?
" "+l+" "+m._scopeSelector:""));return n},updateStyles:function(m){m&&this.mixin(this.customStyle,m);g?b.updateNativeStyleProperties(this,this.customStyle):(this.isAttached?this._needsStyleProperties()?this._updateStyleProperties():this._styleProperties=null:this.__stylePropertiesInvalid=!0,this._styleCache&&this._styleCache.clear(),this._updateRootStyles())},_updateRootStyles:function(m){m=m||this.root;m=Polymer.dom(m)._query(function(t){return t.shadyRoot||t.shadowRoot});for(var n=0,q=m.length,
p;n<q&&(p=m[n]);n++)p.updateStyles&&p.updateStyles()}});Polymer.updateStyles=function(m){d.updateStyles(m);Polymer.Base._updateRootStyles(document)};var h=new Polymer.StyleCache;Polymer.customStyleCache=h;var k=c.SCOPE_NAME,l=b.XSCOPE_NAME})();
Polymer.Base._addFeature({_registerFeatures:function(){this._prepIs();this.factoryImpl&&this._prepConstructor();this._prepStyles()},_finishRegisterFeatures:function(){this._prepTemplate();this._prepShimStyles();this._prepAnnotations();this._prepEffects();this._prepBehaviors();this._prepPropertyInfo();this._prepBindings();this._prepShady()},_prepBehavior:function(a){this._addPropertyEffects(a.properties);this._addComplexObserverEffects(a.observers);this._addHostAttributes(a.hostAttributes)},_initFeatures:function(){this._setupGestures();
this._setupConfigure(this.__data__);this._setupStyleProperties();this._setupDebouncers();this._setupShady();this._registerHost();this._template&&(this._validateApplyShim(),this._poolContent(),this._beginHosting(),this._stampTemplate(),this._endHosting(),this._marshalAnnotationReferences());this._marshalInstanceEffects();this._marshalBehaviors();this._marshalHostAttributes();this._marshalAttributes();this._tryReady()},_marshalBehavior:function(a){a.listeners&&this._listenListeners(a.listeners)}});
(function(){var a=Polymer.StyleProperties,b=Polymer.StyleUtil,c=Polymer.CssParse,d=Polymer.StyleDefaults,e=Polymer.StyleTransformer,g=Polymer.ApplyShim,h=Polymer.Debounce,k=Polymer.Settings,l;Polymer({is:"custom-style",extends:"style",_template:null,properties:{include:String},ready:function(){this.__appliedElement=this.__appliedElement||this;this.__cssBuild=b.getCssBuildType(this);this.__appliedElement!==this&&(this.__appliedElement.__cssBuild=this.__cssBuild);this.ownerDocument!==window.document&&
this.__appliedElement===this&&document.head.appendChild(this);this._tryApply()},attached:function(){this._tryApply()},_tryApply:function(){if(!this._appliesToDocument&&this.parentNode&&"dom-module"!==this.parentNode.localName){this._appliesToDocument=!0;var m=this.__appliedElement;k.useNativeCSSProperties||(this.__needsUpdateStyles=d.hasStyleProperties(),d.addStyle(m));if(m.textContent||this.include)this._apply(!0);else{var n=this,q=new MutationObserver(function(){q.disconnect();n._apply(!0)});q.observe(m,
{childList:!0})}}},_updateStyles:function(){Polymer.updateStyles()},_apply:function(m){var n=this.__appliedElement;this.include&&(n.textContent=b.cssFromModules(this.include,!0)+n.textContent);if(n.textContent){var q=this.__cssBuild,p=b.isTargetedBuild(q);if(!k.useNativeCSSProperties||!p){var t=b.rulesForStyle(n);p||(b.forEachRule(t,function(v){e.documentRule(v)}),k.useNativeCSSProperties&&!q&&g.transform([n]));if(k.useNativeCSSProperties)n.textContent=b.toCssText(t);else{var r=this;n=function(){r._flushCustomProperties()};
m?Polymer.RenderStatus.whenReady(n):n()}}}},_flushCustomProperties:function(){this.__needsUpdateStyles?(this.__needsUpdateStyles=!1,l=h(l,this._updateStyles)):this._applyCustomProperties()},_applyCustomProperties:function(){var m=this.__appliedElement;this._computeStyleProperties();var n=this._styleProperties,q=b.rulesForStyle(m);q&&(m.textContent=b.toCssText(q,function(p){var t=p.cssText=p.parsedCssText;p.propertyInfo&&p.propertyInfo.cssText&&(t=c.removeCustomPropAssignment(t),p.cssText=a.valueForProperties(t,
n))}))}})})();
Polymer.Templatizer={properties:{__hideTemplateChildren__:{observer:"_showHideChildren"}},_instanceProps:Polymer.nob,_parentPropPrefix:"_parent_",templatize:function(a){this._templatized=a;a._content||(a._content=a.content);if(a._content._ctor)this.ctor=a._content._ctor,this._prepParentProperties(this.ctor.prototype,a);else{var b=Object.create(Polymer.Base);this._customPrepAnnotations(b,a);this._prepParentProperties(b,a);b._prepEffects();this._customPrepEffects(b);b._prepBehaviors();b._prepPropertyInfo();
b._prepBindings();b._notifyPathUp=this._notifyPathUpImpl;b._scopeElementClass=this._scopeElementClassImpl;b.listen=this._listenImpl;b._showHideChildren=this._showHideChildrenImpl;b.__setPropertyOrig=this.__setProperty;b.__setProperty=this.__setPropertyImpl;var c=this._constructorImpl,d=function(e,g){c.call(this,e,g)};d.prototype=b;b.constructor=d;this.ctor=a._content._ctor=d}},_getRootDataHost:function(){return this.dataHost&&this.dataHost._rootDataHost||this.dataHost},_showHideChildrenImpl:function(a){for(var b=
this._children,c=0;c<b.length;c++){var d=b[c];!!a!=!!d.__hideTemplateChildren__&&(d.nodeType===Node.TEXT_NODE?a?(d.__polymerTextContent__=d.textContent,d.textContent=""):d.textContent=d.__polymerTextContent__:d.style&&(a?(d.__polymerDisplay__=d.style.display,d.style.display="none"):d.style.display=d.__polymerDisplay__));d.__hideTemplateChildren__=a}},__setPropertyImpl:function(a,b,c,d){d&&d.__hideTemplateChildren__&&"textContent"==a&&(a="__polymerTextContent__");this.__setPropertyOrig(a,b,c,d)},_debounceTemplate:function(a){Polymer.dom.addDebouncer(this.debounce("_debounceTemplate",
a))},_flushTemplates:function(){Polymer.dom.flush()},_customPrepEffects:function(a){var b=a._parentProps,c;for(c in b)a._addPropertyEffect(c,"function",this._createHostPropEffector(c));for(c in this._instanceProps)a._addPropertyEffect(c,"function",this._createInstancePropEffector(c))},_customPrepAnnotations:function(a,b){var c=(a._template=document.createElement("template"))._content=b._content;if(!c._notes){var d=a._rootDataHost;d&&(Polymer.Annotations.prepElement=function(){d._prepElement()});c._notes=
Polymer.Annotations.parseAnnotations(b);Polymer.Annotations.prepElement=null;this._processAnnotations(c._notes)}a._notes=c._notes;a._parentProps=c._parentProps},_prepParentProperties:function(a,b){var c=this._parentProps=a._parentProps;if(this._forwardParentProp&&c){var d=a._parentPropProto,e;if(!d){for(e in this._instanceProps)delete c[e];d=a._parentPropProto=Object.create(null);b!=this&&(Polymer.Bind.prepareModel(d),Polymer.Base.prepareModelNotifyPath(d));for(e in c)a=this._parentPropPrefix+e,c=
[{kind:"function",effect:this._createForwardPropEffector(e),fn:Polymer.Bind._functionEffect},{kind:"notify",fn:Polymer.Bind._notifyEffect,effect:{event:Polymer.CaseMap.camelToDashCase(a)+"-changed"}}],d._propertyEffects=d._propertyEffects||{},d._propertyEffects[a]=c,Polymer.Bind._createAccessors(d,a,c)}var g=this;b!=this&&(Polymer.Bind.prepareInstance(b),b._forwardParentProp=function(h,k){g._forwardParentProp(h,k)});this._extendTemplate(b,d);b._pathEffector=function(h,k,l){return g._pathEffectorImpl(h,
k,l)}}},_createForwardPropEffector:function(a){return function(b,c){this._forwardParentProp(a,c)}},_createHostPropEffector:function(a){var b=this._parentPropPrefix;return function(c,d){this.dataHost._templatized[b+a]=d}},_createInstancePropEffector:function(a){return function(b,c,d,e){e||this.dataHost._forwardInstanceProp(this,a,c)}},_extendTemplate:function(a,b){var c=Object.getOwnPropertyNames(b);b._propertySetter&&(a._propertySetter=b._propertySetter);for(var d=0,e;d<c.length&&(e=c[d]);d++){var g=
a[e];g&&"_propertyEffects"==e?(g=Polymer.Base.mixin({},g),a._propertyEffects=Polymer.Base.mixin(g,b._propertyEffects)):(Object.defineProperty(a,e,Object.getOwnPropertyDescriptor(b,e)),void 0!==g&&a._propertySetter(e,g))}},_showHideChildren:function(){},_forwardInstancePath:function(){},_forwardInstanceProp:function(){},_notifyPathUpImpl:function(a,b){var c=this.dataHost,d=Polymer.Path.root(a);c._forwardInstancePath.call(c,this,a,b);d in c._parentProps&&c._templatized._notifyPath(c._parentPropPrefix+
a,b)},_pathEffectorImpl:function(a,b,c){if(this._forwardParentPath&&0===a.indexOf(this._parentPropPrefix)){var d=a.substring(this._parentPropPrefix.length);Polymer.Path.root(d)in this._parentProps&&this._forwardParentPath(d,b)}Polymer.Base._pathEffector.call(this._templatized,a,b,c)},_constructorImpl:function(a,b){this._rootDataHost=b._getRootDataHost();this._setupConfigure(a);this._registerHost(b);this._beginHosting();this.root=this.instanceTemplate(this._template);this.root.__noContent=!this._notes._hasContent;
this.root.__styleScoped=!0;this._endHosting();this._marshalAnnotatedNodes();this._marshalInstanceEffects();this._marshalAnnotatedListeners();a=[];for(var c=this.root.firstChild;c;c=c.nextSibling)a.push(c),c._templateInstance=this;this._children=a;b.__hideTemplateChildren__&&this._showHideChildren(!0);this._tryReady()},_listenImpl:function(a,b,c){var d=this,e=this._rootDataHost,g=e._createEventHandler(a,b,c);e._listen(a,b,function(h){h.model=d;g(h)})},_scopeElementClassImpl:function(a,b){var c=this._rootDataHost;
return c?c._scopeElementClass(a,b):b},stamp:function(a){a=a||{};if(this._parentProps){var b=this._templatized,c;for(c in this._parentProps)void 0===a[c]&&(a[c]=b[this._parentPropPrefix+c])}return new this.ctor(a,this)},modelForElement:function(a){for(var b;a;)if(b=a._templateInstance)if(b.dataHost!=this)a=b.dataHost;else return b;else a=a.parentNode}};Polymer({is:"dom-template",extends:"template",_template:null,behaviors:[Polymer.Templatizer],ready:function(){this.templatize(this)}});
Polymer._collections=new WeakMap;Polymer.Collection=function(a){Polymer._collections.set(a,this);this.userArray=a;this.store=a.slice();this.initMap()};function Ia(a){if(a&&"#"==a[0])return a.slice(1)}function Ka(a,b){b&&"object"==typeof b?a.omap.delete(b):delete a.pmap[b]}
Polymer.Collection.prototype={constructor:Polymer.Collection,initMap:function(){for(var a=this.omap=new WeakMap,b=this.pmap={},c=this.store,d=0;d<c.length;d++){var e=c[d];e&&"object"==typeof e?a.set(e,d):b[e]=d}},add:function(a){var b=this.store.push(a)-1;a&&"object"==typeof a?this.omap.set(a,b):this.pmap[a]=b;return"#"+b},removeKey:function(a){if(a=Ia(a))Ka(this,this.store[a]),delete this.store[a]},remove:function(a){a=this.getKey(a);this.removeKey(a);return a},getKey:function(a){a=a&&"object"==
typeof a?this.omap.get(a):this.pmap[a];if(void 0!=a)return"#"+a},getKeys:function(){return Object.keys(this.store).map(function(a){return"#"+a})},setItem:function(a,b){if(a=Ia(a)){var c=this.store[a];c&&Ka(this,c);b&&"object"==typeof b?this.omap.set(b,a):this.pmap[b]=a;this.store[a]=b}},getItem:function(a){if(a=Ia(a))return this.store[a]},getItems:function(){var a=[],b=this.store,c;for(c in b)a.push(b[c]);return a}};Polymer.Collection.get=function(a){return Polymer._collections.get(a)||new Polymer.Collection(a)};
Polymer.Collection.applySplices=function(a,b){a=Polymer._collections.get(a);if(a){for(var c={},d=0,e;d<b.length&&(e=b[d]);d++){e.addedKeys=[];for(var g=0;g<e.removed.length;g++){var h=a.getKey(e.removed[g]);c[h]=c[h]?null:-1}for(g=0;g<e.addedCount;g++){var k=a.userArray[e.index+g];h=a.getKey(k);h=void 0===h?a.add(k):h;c[h]=c[h]?null:1;e.addedKeys.push(h)}}b=[];e=[];for(h in c)0>c[h]&&(a.removeKey(h),b.push(h)),0<c[h]&&e.push(h);h=[{removed:b,added:e}]}else h=null;return h};
function DomRepeatElement(){}fa=DomRepeatElement.prototype;fa.ctor=function(){};fa.stamp=function(){};fa.templatize=function(){};fa.modelForElement=function(){};fa._debounceTemplate=function(){};fa._setRenderedItemCount=function(){};
Polymer({is:"dom-repeat",extends:"template",_template:null,properties:{items:{type:Array},as:{type:String,value:"item"},indexAs:{type:String,value:"index"},sort:{type:Function,observer:"_sortChanged"},filter:{type:Function,observer:"_filterChanged"},observe:{type:String,observer:"_observeChanged"},delay:Number,renderedItemCount:{type:Number,notify:!Polymer.Settings.suppressTemplateNotifications,readOnly:!0},initialCount:{type:Number,observer:"_initializeChunking"},targetFramerate:{type:Number,value:20},
notifyDomChange:{type:Boolean},_targetFrameTime:{type:Number,computed:"_computeFrameTime(targetFramerate)"}},behaviors:[Polymer.Templatizer],observers:["_itemsChanged(items.*)"],created:function(){this._instances=[];this._pool=[];this._limit=Infinity;var a=this;this._boundRenderChunk=function(){a._renderChunk()}},detached:function(){this.__isDetached=!0;for(var a=0;a<this._instances.length;a++)this._detachInstance(a)},attached:function(){if(this.__isDetached){this.__isDetached=!1;var a=Polymer.dom(this).parentNode;
if(a.localName==this.is){var b=a;a=Polymer.dom(a).parentNode}else b=this;a=Polymer.dom(a);for(var c=0;c<this._instances.length;c++)this._attachInstance(c,a,b)}},ready:function(){this._instanceProps={__key__:!0};this._instanceProps[this.as]=!0;this._instanceProps[this.indexAs]=!0;this.ctor||this.templatize(this)},_sortChanged:function(a){var b=this._getRootDataHost();this._sortFn=a&&("function"==typeof a?a:function(){return b[a].apply(b,arguments)});this._needFullRefresh=!0;this.items&&this._debounceTemplate(this._render)},
_filterChanged:function(a){var b=this._getRootDataHost();this._filterFn=a&&("function"==typeof a?a:function(){return b[a].apply(b,arguments)});this._needFullRefresh=!0;this.items&&this._debounceTemplate(this._render)},_computeFrameTime:function(a){return Math.ceil(1E3/a)},_initializeChunking:function(){this.initialCount&&(this._chunkCount=this._limit=this.initialCount,this._lastChunkTime=performance.now())},_tryRenderChunk:function(){this.items&&this._limit<this.items.length&&this.debounce("renderChunk",
this._requestRenderChunk)},_requestRenderChunk:function(){requestAnimationFrame(this._boundRenderChunk)},_renderChunk:function(){var a=performance.now();this._chunkCount=Math.round(this._targetFrameTime/(a-this._lastChunkTime)*this._chunkCount)||1;this._limit+=this._chunkCount;this._lastChunkTime=a;this._debounceTemplate(this._render)},_observeChanged:function(){this._observePaths=this.observe&&this.observe.replace(".*",".").split(" ")},_itemsChanged:function(a){if("items"==a.path)Array.isArray(this.items)?
this.collection=Polymer.Collection.get(this.items):this.items?this._error(this._logf("dom-repeat","expected array for `items`, found",this.items)):this.collection=null,this._keySplices=[],this._indexSplices=[],this._needFullRefresh=!0,this._initializeChunking(),this._debounceTemplate(this._render);else if("items.splices"==a.path)this._keySplices=this._keySplices.concat(a.value.keySplices),this._indexSplices=this._indexSplices.concat(a.value.indexSplices),this._debounceTemplate(this._render);else{var b=
a.path.slice(6);this._forwardItemPath(b,a.value);this._checkObservedPaths(b)}},_checkObservedPaths:function(a){if(this._observePaths){a=a.substring(a.indexOf(".")+1);for(var b=this._observePaths,c=0;c<b.length;c++)if(0===a.indexOf(b[c])){this._needFullRefresh=!0;this.delay?this.debounce("render",this._render,this.delay):this._debounceTemplate(this._render);break}}},render:function(){this._needFullRefresh=!0;this._debounceTemplate(this._render);this._flushTemplates()},_render:function(){this._needFullRefresh?
(this._applyFullRefresh(),this._needFullRefresh=!1):this._keySplices.length&&(this._sortFn?this._applySplicesUserSort(this._keySplices):this._filterFn?this._applyFullRefresh():this._applySplicesArrayOrder(this._indexSplices));this._keySplices=[];this._indexSplices=[];for(var a=this._keyToInstIdx={},b=this._instances.length-1;0<=b;b--){var c=this._instances[b];c.isPlaceholder&&b<this._limit?c=this._insertInstance(b,c.__key__):!c.isPlaceholder&&b>=this._limit&&(c=this._downgradeInstance(b,c.__key__));
a[c.__key__]=b;c.isPlaceholder||c.__setProperty(this.indexAs,b,!0)}this._pool.length=0;this._setRenderedItemCount(this._instances.length);Polymer.Settings.suppressTemplateNotifications&&!this.notifyDomChange||this.fire("dom-change");this._tryRenderChunk()},_applyFullRefresh:function(){var a=this.collection;if(this._sortFn)var b=a?a.getKeys():[];else{b=[];var c=this.items;if(c)for(var d=0;d<c.length;d++)b.push(a.getKey(c[d]))}var e=this;this._filterFn&&(b=b.filter(function(h){return e._filterFn(a.getItem(h))}));
this._sortFn&&b.sort(function(h,k){return e._sortFn(a.getItem(h),a.getItem(k))});for(d=0;d<b.length;d++){c=b[d];var g=this._instances[d];g?(g.__key__=c,!g.isPlaceholder&&d<this._limit&&g.__setProperty(this.as,a.getItem(c),!0)):d<this._limit?this._insertInstance(d,c):this._insertPlaceholder(d,c)}for(b=this._instances.length-1;b>=d;b--)this._detachAndRemoveInstance(b)},_numericSort:function(a,b){return a-b},_applySplicesUserSort:function(a){for(var b=this.collection,c={},d,e=0,g;e<a.length&&(g=a[e]);e++){for(var h=
0;h<g.removed.length;h++)d=g.removed[h],c[d]=c[d]?null:-1;for(h=0;h<g.added.length;h++)d=g.added[h],c[d]=c[d]?null:1}g=[];a=[];for(d in c)-1===c[d]&&g.push(this._keyToInstIdx[d]),1===c[d]&&a.push(d);if(g.length)for(g.sort(this._numericSort),e=g.length-1;0<=e;e--)c=g[e],void 0!==c&&this._detachAndRemoveInstance(c);var k=this;if(a.length)for(this._filterFn&&(a=a.filter(function(l){return k._filterFn(b.getItem(l))})),a.sort(function(l,m){return k._sortFn(b.getItem(l),b.getItem(m))}),e=c=0;e<a.length;e++)c=
this._insertRowUserSort(c,a[e])},_insertRowUserSort:function(a,b){for(var c=this.collection,d=c.getItem(b),e=this._instances.length-1,g=-1;a<=e;){var h=a+e>>1,k=this._sortFn(c.getItem(this._instances[h].__key__),d);if(0>k)a=h+1;else if(0<k)e=h-1;else{g=h;break}}0>g&&(g=e+1);this._insertPlaceholder(g,b);return g},_applySplicesArrayOrder:function(a){for(var b=0,c;b<a.length&&(c=a[b]);b++){for(var d=0;d<c.removed.length;d++)this._detachAndRemoveInstance(c.index);for(d=0;d<c.addedKeys.length;d++)this._insertPlaceholder(c.index+
d,c.addedKeys[d])}},_detachInstance:function(a){a=this._instances[a];if(!a.isPlaceholder){for(var b=0;b<a._children.length;b++){var c=a._children[b];Polymer.dom(a.root).appendChild(c)}return a}},_attachInstance:function(a,b,c){a=this._instances[a];a.isPlaceholder||b.insertBefore(a.root,c)},_detachAndRemoveInstance:function(a){var b=this._detachInstance(a);b&&this._pool.push(b);this._instances.splice(a,1)},_insertPlaceholder:function(a,b){this._instances.splice(a,0,{isPlaceholder:!0,__key__:b})},_stampInstance:function(a,
b){var c={__key__:b};c[this.as]=this.collection.getItem(b);c[this.indexAs]=a;return this.stamp(c)},_insertInstance:function(a,b){var c=this._pool.pop();c?(c.__setProperty(this.as,this.collection.getItem(b),!0),c.__setProperty("__key__",b,!0)):c=this._stampInstance(a,b);b=(b=this._instances[a+1])&&!b.isPlaceholder?b._children[0]:this;var d=Polymer.dom(this).parentNode;d.localName==this.is&&(b==this&&(b=d),d=Polymer.dom(d).parentNode);Polymer.dom(d).insertBefore(c.root,b);return this._instances[a]=
c},_downgradeInstance:function(a,b){var c=this._detachInstance(a);c&&this._pool.push(c);c={isPlaceholder:!0,__key__:b};return this._instances[a]=c},_showHideChildren:function(a){for(var b=0;b<this._instances.length;b++)this._instances[b].isPlaceholder||this._instances[b]._showHideChildren(a)},_forwardInstanceProp:function(a,b,c){b==this.as&&(a=this._sortFn||this._filterFn?this.items.indexOf(this.collection.getItem(a.__key__)):a[this.indexAs],this.set("items."+a,c))},_forwardInstancePath:function(a,
b,c){0===b.indexOf(this.as+".")&&this._notifyPath("items."+a.__key__+"."+b.slice(this.as.length+1),c)},_forwardParentProp:function(a,b){for(var c=this._instances,d=0,e;d<c.length&&(e=c[d]);d++)e.isPlaceholder||e.__setProperty(a,b,!0)},_forwardParentPath:function(a,b){for(var c=this._instances,d=0,e;d<c.length&&(e=c[d]);d++)e.isPlaceholder||e._notifyPath(a,b,!0)},_forwardItemPath:function(a,b){if(this._keyToInstIdx){var c=a.indexOf("."),d=this._instances[this._keyToInstIdx[a.substring(0,0>c?a.length:
c)]];d&&!d.isPlaceholder&&(0<=c?(a=this.as+"."+a.substring(c+1),d._notifyPath(a,b,!0)):d.__setProperty(this.as,b,!0))}},itemForElement:function(a){return(a=this.modelForElement(a))&&a[this.as]},keyForElement:function(a){return(a=this.modelForElement(a))&&a.__key__},indexForElement:function(a){return(a=this.modelForElement(a))&&a[this.indexAs]}});
Polymer({is:"array-selector",_template:null,properties:{items:{type:Array,observer:"clearSelection"},multi:{type:Boolean,value:!1,observer:"clearSelection"},selected:{type:Object,notify:!0},selectedItem:{type:Object,notify:!0},toggle:{type:Boolean,value:!1}},clearSelection:function(){if(Array.isArray(this.selected))for(var a=0;a<this.selected.length;a++)this.unlinkPaths("selected."+a);else this.unlinkPaths("selected"),this.unlinkPaths("selectedItem");if(this.multi){if(!this.selected||this.selected.length)this.selected=
[],this._selectedColl=Polymer.Collection.get(this.selected)}else this._selectedColl=this.selected=null;this.selectedItem=null},isSelected:function(a){return this.multi?void 0!==this._selectedColl.getKey(a):this.selected==a},deselect:function(a){if(this.multi){if(this.isSelected(a)){var b=this._selectedColl.getKey(a);this.arrayDelete("selected",a);this.unlinkPaths("selected."+b)}}else this.selectedItem=this.selected=null,this.unlinkPaths("selected"),this.unlinkPaths("selectedItem")},select:function(a){var b=
Polymer.Collection.get(this.items).getKey(a);this.multi?this.isSelected(a)?this.toggle&&this.deselect(a):(this.push("selected",a),a=this._selectedColl.getKey(a),this.linkPaths("selected."+a,"items."+b)):this.toggle&&a==this.selected?this.deselect():(this.selectedItem=this.selected=a,this.linkPaths("selected","items."+b),this.linkPaths("selectedItem","items."+b))}});
Polymer({is:"dom-if",extends:"template",_template:null,properties:{"if":{type:Boolean,value:!1,observer:"_queueRender"},restamp:{type:Boolean,value:!1,observer:"_queueRender"},notifyDomChange:{type:Boolean}},behaviors:[Polymer.Templatizer],_queueRender:function(){this._debounceTemplate(this._render)},detached:function(){var a=this.parentNode;a&&a.localName==this.is&&(a=Polymer.dom(a).parentNode);a&&(a.nodeType!=Node.DOCUMENT_FRAGMENT_NODE||Polymer.Settings.hasShadow&&a instanceof ShadowRoot)||this._teardownInstance()},
attached:function(){this.if&&this.ctor&&this.async(this._ensureInstance)},render:function(){this._flushTemplates()},_render:function(){this.if?(this.ctor||this.templatize(this),this._ensureInstance(),this._showHideChildren()):this.restamp&&this._teardownInstance();!this.restamp&&this._instance&&this._showHideChildren();this.if!=this._lastIf&&(Polymer.Settings.suppressTemplateNotifications&&!this.notifyDomChange||this.fire("dom-change"),this._lastIf=this.if)},_ensureInstance:function(){var a=Polymer.dom(this).parentNode;
if(a&&a.localName==this.is){var b=a;a=Polymer.dom(a).parentNode}else b=this;if(a)if(this._instance){var c=this._instance._children;if(c&&c.length&&Polymer.dom(b).previousSibling!==c[c.length-1])for(var d=0,e;d<c.length&&(e=c[d]);d++)Polymer.dom(a).insertBefore(e,b)}else this._instance=this.stamp(),c=this._instance.root,Polymer.dom(a).insertBefore(c,b)},_teardownInstance:function(){if(this._instance){var a=this._instance._children;if(a&&a.length)for(var b=Polymer.dom(Polymer.dom(a[0]).parentNode),
c=0,d;c<a.length&&(d=a[c]);c++)b.removeChild(d);this._instance=null}},_showHideChildren:function(){var a=this.__hideTemplateChildren__||!this.if;this._instance&&this._instance._showHideChildren(a)},_forwardParentProp:function(a,b){this._instance&&this._instance.__setProperty(a,b,!0)},_forwardParentPath:function(a,b){this._instance&&this._instance._notifyPath(a,b,!0)}});
Polymer({is:"dom-bind",properties:{notifyDomChange:{type:Boolean}},extends:"template",_template:null,created:function(){var a=this;Polymer.RenderStatus.whenReady(function(){"loading"==document.readyState?document.addEventListener("DOMContentLoaded",function(){a._markImportsReady()}):a._markImportsReady()})},_ensureReady:function(){this._readied||this._readySelf()},_markImportsReady:function(){this._importsReady=!0;this._ensureReady()},_registerFeatures:function(){this._prepConstructor()},_insertChildren:function(){var a=
Polymer.dom(this).parentNode;if(a.localName==this.is){var b=a;a=Polymer.dom(a).parentNode}else b=this;Polymer.dom(a).insertBefore(this.root,b)},_removeChildren:function(){if(this._children)for(var a=0;a<this._children.length;a++)this.root.appendChild(this._children[a])},_initFeatures:function(){},_scopeElementClass:function(a,b){return this.dataHost?this.dataHost._scopeElementClass(a,b):b},_configureInstanceProperties:function(){},_prepConfigure:function(){var a={},b;for(b in this._propertyEffects)a[b]=
this[b];var c=this._setupConfigure;this._setupConfigure=function(){c.call(this,a)}},attached:function(){this._importsReady&&this.render()},detached:function(){this._removeChildren()},render:function(){this._ensureReady();this._children||(this._template=this,this._prepAnnotations(),this._prepEffects(),this._prepBehaviors(),this._prepConfigure(),this._prepBindings(),this._prepPropertyInfo(),Polymer.Base._initFeatures.call(this),this._children=Polymer.TreeApi.arrayCopyChildNodes(this.root));this._insertChildren();
Polymer.Settings.suppressTemplateNotifications&&!this.notifyDomChange||this.fire("dom-change")}});