// @license
// Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
// This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
// The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
// The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
// Code distributed by Google as part of the polymer project is also
// subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

(function(){function a(){document.body.removeAttribute("unresolved")}window.WebComponents?addEventListener("WebComponentsReady",a):"interactive"===document.readyState||"complete"===document.readyState?a():addEventListener("DOMContentLoaded",a)})();var na=window,va=window.Polymer||{};if(!va.noUrlSettings)for(var wa=location.search.slice(1).split("\x26"),Da=0,Ga;Da<wa.length&&(Ga=wa[Da]);Da++)Ga=Ga.split("\x3d"),Ga[0]&&(va[Ga[0]]=Ga[1]||!0);va.wantShadow="shadow"===va.dom;va.hasShadow=!!Element.prototype.createShadowRoot;
va.nativeShadow=va.hasShadow&&!window.ShadowDOMPolyfill;va.useShadow=va.wantShadow&&va.hasShadow;va.hasNativeImports="import"in document.createElement("link");va.useNativeImports=va.hasNativeImports;va.useNativeCustomElements=!window.CustomElements||window.CustomElements.useNative;va.useNativeShadow=va.useShadow&&va.nativeShadow;va.usePolyfillProto=!va.useNativeCustomElements&&!Object.__proto__;
va.hasNativeCSSProperties=!navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)&&window.CSS&&CSS.supports&&CSS.supports("box-shadow","0 0 0 var(--foo)");va.useNativeCSSProperties=va.hasNativeCSSProperties&&va.lazyRegister&&va.useNativeCSSProperties;va.isIE=navigator.userAgent.match("Trident");va.passiveTouchGestures=va.passiveTouchGestures||!1;na.Polymer={Settings:va};
(function(){function a(d){var e=Polymer.Base;d.extends&&(e=Polymer.Base._getExtendedPrototype(d.extends));d=Polymer.Base.chainObject(d,e);d.registerCallback();return d}var b=window.Polymer;window.Polymer=function(d){"function"===typeof d&&(d=d.prototype);d||(d={});d=a(d);var e=d===d.constructor.prototype?d.constructor:null,g={prototype:d};d.extends&&(g.extends=d.extends);Polymer.telemetry._registrate(d);d=document.registerElement(d.is,g);return e||d};if(b)for(var c in b)Polymer[c]=b[c];Polymer.Class=
function(d){d.factoryImpl||(d.factoryImpl=function(){});return a(d).constructor}})();Polymer.telemetry={registrations:[],_regLog:function(a){console.log("["+a.is+"]: registered")},_registrate:function(a){this.registrations.push(a);Polymer.log&&this._regLog(a)},dumpRegistrations:function(){this.registrations.forEach(this._regLog)}};Object.defineProperty(window,"currentImport",{enumerable:!0,configurable:!0,get:function(){return(document._currentScript||document.currentScript||{}).ownerDocument}});
Polymer.RenderStatus={_ready:!1,_callbacks:[],whenReady:function(a){this._ready?a():this._callbacks.push(a)},_makeReady:function(){this._ready=!0;for(var a=0;a<this._callbacks.length;a++)this._callbacks[a]();this._callbacks=[]},_catchFirstRender:function(){requestAnimationFrame(function(){Polymer.RenderStatus._makeReady()})},_afterNextRenderQueue:[],_waitingNextRender:!1,afterNextRender:function(a,b,c){this._watchNextRender();this._afterNextRenderQueue.push([a,b,c])},hasRendered:function(){return this._ready},
_watchNextRender:function(){if(!this._waitingNextRender){this._waitingNextRender=!0;var a=function(){Polymer.RenderStatus._flushNextRender()};this._ready?requestAnimationFrame(a):this.whenReady(a)}},_flushNextRender:function(){var a=this;setTimeout(function(){a._flushRenderCallbacks(a._afterNextRenderQueue);a._afterNextRenderQueue=[];a._waitingNextRender=!1})},_flushRenderCallbacks:function(a){for(var b=0,c;b<a.length;b++)c=a[b],c[1].apply(c[0],c[2]||Polymer.nar)}};
window.HTMLImports?HTMLImports.whenReady(function(){Polymer.RenderStatus._catchFirstRender()}):Polymer.RenderStatus._catchFirstRender();Polymer.ImportStatus=Polymer.RenderStatus;Polymer.ImportStatus.whenLoaded=Polymer.ImportStatus.whenReady;
(function(){var a=Polymer.Settings;Polymer.Base={__isPolymerInstance__:!0,_addFeature:function(d){this.mixin(this,d)},registerCallback:function(){if("max"!==a.lazyRegister){this._desugarBehaviors();for(var d=0,e;d<this.behaviors.length;d++)e=this.behaviors[d],e.beforeRegister&&e.beforeRegister.call(this)}this.beforeRegister&&this.beforeRegister();this._registerFeatures();a.lazyRegister||this.ensureRegisterFinished()},createdCallback:function(){if(a.disableUpgradeEnabled){if(this.hasAttribute("disable-upgrade")){this._propertySetter=
b;this._configValue=null;this.__data__={};return}this.__hasInitialized=!0}this.__initialize()},__initialize:function(){this.__hasRegisterFinished||this._ensureRegisterFinished(this.__proto__);Polymer.telemetry.instanceCount++;this.root=this;for(var d=0,e;d<this.behaviors.length;d++)e=this.behaviors[d],e.created&&e.created.call(this);this.created&&this.created();this._initFeatures()},ensureRegisterFinished:function(){this._ensureRegisterFinished(this)},_ensureRegisterFinished:function(d){if(d.__hasRegisterFinished!==
d.is||!d.is){if("max"===a.lazyRegister){d._desugarBehaviors();for(var e=0,g;e<d.behaviors.length;e++)g=d.behaviors[e],g.beforeRegister&&g.beforeRegister.call(d)}d.__hasRegisterFinished=d.is;d._finishRegisterFeatures&&d._finishRegisterFeatures();for(e=0;e<d.behaviors.length;e++)g=d.behaviors[e],g.registered&&g.registered.call(d);d.registered&&d.registered();a.usePolyfillProto&&d!==this&&d.extend(this,d)}},attachedCallback:function(){var d=this;Polymer.RenderStatus.whenReady(function(){d.isAttached=
!0;for(var e=0,g;e<d.behaviors.length;e++)g=d.behaviors[e],g.attached&&g.attached.call(d);d.attached&&d.attached()})},detachedCallback:function(){var d=this;Polymer.RenderStatus.whenReady(function(){d.isAttached=!1;for(var e=0,g;e<d.behaviors.length;e++)g=d.behaviors[e],g.detached&&g.detached.call(d);d.detached&&d.detached()})},attributeChangedCallback:function(d,e,g){this._attributeChangedImpl(d);for(var h=0,k;h<this.behaviors.length;h++)k=this.behaviors[h],k.attributeChanged&&k.attributeChanged.call(this,
d,e,g);this.attributeChanged&&this.attributeChanged(d,e,g)},_attributeChangedImpl:function(d){this._setAttributeToProperty(this,d)},extend:function(d,e){if(d&&e)for(var g=Object.getOwnPropertyNames(e),h=0,k;h<g.length&&(k=g[h]);h++)this.copyOwnProperty(k,e,d);return d||e},mixin:function(d,e){for(var g in e)d[g]=e[g];return d},copyOwnProperty:function(d,e,g){(e=Object.getOwnPropertyDescriptor(e,d))&&Object.defineProperty(g,d,e)},_logger:function(d,e){1===e.length&&Array.isArray(e[0])&&(e=e[0]);switch(d){case "log":case "warn":case "error":console[d].apply(console,
e)}},_log:function(){this._logger("log",Array.prototype.slice.call(arguments,0))},_warn:function(){this._logger("warn",Array.prototype.slice.call(arguments,0))},_error:function(){this._logger("error",Array.prototype.slice.call(arguments,0))},_logf:function(){return this._logPrefix.concat(this.is).concat(Array.prototype.slice.call(arguments,0))}};Polymer.Base._logPrefix=window.chrome&&!/edge/i.test(navigator.userAgent)||/firefox/i.test(navigator.userAgent)?["%c[%s::%s]:","font-weight: bold; background-color:#EEEE00;"]:
["[%s::%s]:"];Polymer.Base.chainObject=function(d,e){d&&e&&d!==e&&(Object.__proto__||(d=Polymer.Base.extend(Object.create(e),d)),d.__proto__=e);return d};Polymer.Base=Polymer.Base.chainObject(Polymer.Base,HTMLElement.prototype);Polymer.BaseDescriptors={};if(a.disableUpgradeEnabled){var b=function(d,e){this.__data__[d]=e};var c=Polymer.Base.attributeChangedCallback;Polymer.Base.attributeChangedCallback=function(d,e,g){this.__hasInitialized||"disable-upgrade"!==d||(this.__hasInitialized=!0,this._propertySetter=
Polymer.Bind._modelApi._propertySetter,this._configValue=Polymer.Base._configValue,this.__initialize());c.call(this,d,e,g)}}Polymer.instanceof=window.CustomElements?CustomElements.instanceof:function(d,e){return d instanceof e};Polymer.isInstance=function(d){return!(!d||!d.__isPolymerInstance__)};Polymer.telemetry.instanceCount=0})();
(function(){function a(){return document.createElement("dom-module")}var b={},c={};a.prototype=Object.create(HTMLElement.prototype);Polymer.Base.mixin(a.prototype,{createdCallback:function(){this.register()},register:function(e){if(e=e||this.id||this.getAttribute("name")||this.getAttribute("is"))this.id=e,b[e]=this,c[e.toLowerCase()]=this},import:function(e,g){if(e){var h=b[e]||c[e.toLowerCase()];if(!h){if(d){h=document._currentScript||document.currentScript;h=(h&&h.ownerDocument||document).querySelectorAll("dom-module");
for(var k=h.length-1,l;0<=k&&(l=h[k])&&!l.__upgraded__;k--)CustomElements.upgrade(l)}h=b[e]||c[e.toLowerCase()]}h&&g&&(h=h.querySelector(g));return h}}});Object.defineProperty(a.prototype,"constructor",{value:a,configurable:!0,writable:!0});var d=window.CustomElements&&!CustomElements.useNative;document.registerElement("dom-module",a)})();
Polymer.Base._addFeature({_prepIs:function(){if(!this.is){var a=(document._currentScript||document.currentScript).parentNode;"dom-module"===a.localName&&(this.is=a.id||a.getAttribute("name")||a.getAttribute("is"))}this.is&&(this.is=this.is.toLowerCase())}});
Polymer.Base._addFeature({behaviors:[],_desugarBehaviors:function(){this.behaviors.length&&(this.behaviors=this._desugarSomeBehaviors(this.behaviors))},_desugarSomeBehaviors:function(a){var b=[];a=this._flattenBehaviorsList(a);for(var c=a.length-1;0<=c;c--){var d=a[c];-1===b.indexOf(d)&&(this._mixinBehavior(d),b.unshift(d))}return b},_flattenBehaviorsList:function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];d instanceof Array?b=b.concat(this._flattenBehaviorsList(d)):d?b.push(d):this._warn(this._logf("_flattenBehaviorsList",
"behavior is null, check for missing or 404 import"))}return b},_mixinBehavior:function(a){for(var b=Object.getOwnPropertyNames(a),c=a._noAccessors,d=0,e;d<b.length&&(e=b[d]);d++)Polymer.Base._behaviorProperties[e]||this.hasOwnProperty(e)||(c?this[e]=a[e]:this.copyOwnProperty(e,a,this))},_prepBehaviors:function(){this._prepFlattenedBehaviors(this.behaviors)},_prepFlattenedBehaviors:function(a){for(var b=0,c=a.length;b<c;b++)this._prepBehavior(a[b]);this._prepBehavior(this)},_marshalBehaviors:function(){for(var a=
0;a<this.behaviors.length;a++)this._marshalBehavior(this.behaviors[a]);this._marshalBehavior(this)}});Polymer.Base._behaviorProperties={hostAttributes:!0,beforeRegister:!0,registered:!0,properties:!0,observers:!0,listeners:!0,created:!0,attached:!0,detached:!0,attributeChanged:!0,ready:!0,_noAccessors:!0};
Polymer.Base._addFeature({_getExtendedPrototype:function(a){return this._getExtendedNativePrototype(a)},_nativePrototypes:{},_getExtendedNativePrototype:function(a){var b=this._nativePrototypes[a];if(!b){b=Object.create(this.getNativePrototype(a));for(var c=Object.getOwnPropertyNames(Polymer.Base),d=0,e;d<c.length&&(e=c[d]);d++)Polymer.BaseDescriptors[e]||(b[e]=Polymer.Base[e]);Object.defineProperties(b,Polymer.BaseDescriptors);this._nativePrototypes[a]=b}return b},getNativePrototype:function(a){return Object.getPrototypeOf(document.createElement(a))}});
Polymer.Base._addFeature({_prepConstructor:function(){function a(){return this._factory(arguments)}this._factoryArgs=this.extends?[this.extends,this.is]:[this.is];this.hasOwnProperty("extends")&&(a.extends=this.extends);Object.defineProperty(this,"constructor",{value:a,writable:!0,configurable:!0});a.prototype=this},_factory:function(a){var b=document.createElement.apply(document,this._factoryArgs);this.factoryImpl&&this.factoryImpl.apply(b,a);return b}});Polymer.nob=Object.create(null);
Polymer.Base._addFeature({getPropertyInfo:function(a){var b=this._getPropertyInfo(a,this.properties);if(!b)for(var c=0;c<this.behaviors.length;c++)if(b=this._getPropertyInfo(a,this.behaviors[c].properties))return b;return b||Polymer.nob},_getPropertyInfo:function(a,b){var c=b&&b[a];"function"===typeof c&&(c=b[a]={type:c});c&&(c.defined=!0);return c},_prepPropertyInfo:function(){this._propertyInfo={};for(var a=0;a<this.behaviors.length;a++)this._addPropertyInfo(this._propertyInfo,this.behaviors[a].properties);
this._addPropertyInfo(this._propertyInfo,this.properties);this._addPropertyInfo(this._propertyInfo,this._propertyEffects)},_addPropertyInfo:function(a,b){if(b){var c;for(c in b){var d=a[c];var e=b[c];if("_"!==c[0]||e.readOnly)a[c]?(d.type||(d.type=e.type),d.readOnly||(d.readOnly=e.readOnly)):a[c]={type:"function"===typeof e?e:e.type,readOnly:e.readOnly,attribute:Polymer.CaseMap.camelToDashCase(c)}}}}});var Ha={configurable:!0,writable:!0,enumerable:!0,value:{}};
Polymer.BaseDescriptors.properties=Ha;Object.defineProperty(Polymer.Base,"properties",Ha);Polymer.CaseMap={_caseMap:{},_rx:{dashToCamel:/-[a-z]/g,camelToDash:/([A-Z])/g},dashToCamelCase:function(a){return this._caseMap[a]||(this._caseMap[a]=0>a.indexOf("-")?a:a.replace(this._rx.dashToCamel,function(b){return b[1].toUpperCase()}))},camelToDashCase:function(a){return this._caseMap[a]||(this._caseMap[a]=a.replace(this._rx.camelToDash,"-$1").toLowerCase())}};
Polymer.Base._addFeature({_addHostAttributes:function(a){this._aggregatedAttributes||(this._aggregatedAttributes={});a&&this.mixin(this._aggregatedAttributes,a)},_marshalHostAttributes:function(){this._aggregatedAttributes&&this._applyAttributes(this,this._aggregatedAttributes)},_applyAttributes:function(a,b){for(var c in b)this.hasAttribute(c)||"class"===c||this.serializeValueToAttribute(b[c],c,this)},_marshalAttributes:function(){this._takeAttributesToModel(this)},_takeAttributesToModel:function(a){if(this.hasAttributes())for(var b in this._propertyInfo){var c=
this._propertyInfo[b];this.hasAttribute(c.attribute)&&this._setAttributeToProperty(a,c.attribute,b,c)}},_setAttributeToProperty:function(a,b,c,d){this._serializing||(c=c||Polymer.CaseMap.dashToCamelCase(b),(d=d||this._propertyInfo&&this._propertyInfo[c])&&!d.readOnly&&(b=this.getAttribute(b),a[c]=this.deserialize(b,d.type)))},_serializing:!1,reflectPropertyToAttribute:function(a,b,c){this._serializing=!0;c=void 0===c?this[a]:c;this.serializeValueToAttribute(c,b||Polymer.CaseMap.camelToDashCase(a));
this._serializing=!1},serializeValueToAttribute:function(a,b,c){a=this.serialize(a);c=c||this;void 0===a?c.removeAttribute(b):c.setAttribute(b,a)},deserialize:function(a,b){switch(b){case Number:a=Number(a);break;case Boolean:a=null!=a;break;case Object:try{a=JSON.parse(a)}catch(c){}break;case Array:try{a=JSON.parse(a)}catch(c){a=null,console.warn("Polymer::Attributes: couldn`t decode Array as JSON")}break;case Date:a=new Date(a)}return a},serialize:function(a){switch(typeof a){case "boolean":return a?
"":void 0;case "object":if(a instanceof Date)return a.toString();if(a)try{return JSON.stringify(a)}catch(b){return""}default:return null!=a?a:void 0}}});Polymer.version="1.11.3";Polymer.Base._addFeature({_registerFeatures:function(){this._prepIs();this._prepBehaviors();this._prepConstructor();this._prepPropertyInfo()},_prepBehavior:function(a){this._addHostAttributes(a.hostAttributes)},_marshalBehavior:function(){},_initFeatures:function(){this._marshalHostAttributes();this._marshalBehaviors()}});
